/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#ifndef TYPES_UAFX_DATA_GENERATED_HANDLING_H_
#define TYPES_UAFX_DATA_GENERATED_HANDLING_H_

#include "types_uafx_data_generated.h"

_UA_BEGIN_DECLS

#if defined(__GNUC__) && __GNUC__ >= 4 && __GNUC_MINOR__ >= 6
# pragma GCC diagnostic push
# pragma GCC diagnostic ignored "-Wmissing-field-initializers"
# pragma GCC diagnostic ignored "-Wmissing-braces"
#endif


/* PubSubCommunicationConfigurationDataType */
static UA_INLINE void
UA_PubSubCommunicationConfigurationDataType_init(UA_PubSubCommunicationConfigurationDataType *p) {
    memset(p, 0, sizeof(UA_PubSubCommunicationConfigurationDataType));
}

static UA_INLINE UA_PubSubCommunicationConfigurationDataType *
UA_PubSubCommunicationConfigurationDataType_new(void) {
    return (UA_PubSubCommunicationConfigurationDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_PubSubCommunicationConfigurationDataType_copy(const UA_PubSubCommunicationConfigurationDataType *src, UA_PubSubCommunicationConfigurationDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_PubSubCommunicationConfigurationDataType_deleteMembers(UA_PubSubCommunicationConfigurationDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONDATATYPE]);
}

static UA_INLINE void
UA_PubSubCommunicationConfigurationDataType_clear(UA_PubSubCommunicationConfigurationDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONDATATYPE]);
}

static UA_INLINE void
UA_PubSubCommunicationConfigurationDataType_delete(UA_PubSubCommunicationConfigurationDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONDATATYPE]);
}static UA_INLINE UA_Boolean
UA_PubSubCommunicationConfigurationDataType_equal(const UA_PubSubCommunicationConfigurationDataType *p1, const UA_PubSubCommunicationConfigurationDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONDATATYPE]) == UA_ORDER_EQ);
}



/* PubSubCommunicationConfigurationResultDataType */
static UA_INLINE void
UA_PubSubCommunicationConfigurationResultDataType_init(UA_PubSubCommunicationConfigurationResultDataType *p) {
    memset(p, 0, sizeof(UA_PubSubCommunicationConfigurationResultDataType));
}

static UA_INLINE UA_PubSubCommunicationConfigurationResultDataType *
UA_PubSubCommunicationConfigurationResultDataType_new(void) {
    return (UA_PubSubCommunicationConfigurationResultDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONRESULTDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_PubSubCommunicationConfigurationResultDataType_copy(const UA_PubSubCommunicationConfigurationResultDataType *src, UA_PubSubCommunicationConfigurationResultDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONRESULTDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_PubSubCommunicationConfigurationResultDataType_deleteMembers(UA_PubSubCommunicationConfigurationResultDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONRESULTDATATYPE]);
}

static UA_INLINE void
UA_PubSubCommunicationConfigurationResultDataType_clear(UA_PubSubCommunicationConfigurationResultDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONRESULTDATATYPE]);
}

static UA_INLINE void
UA_PubSubCommunicationConfigurationResultDataType_delete(UA_PubSubCommunicationConfigurationResultDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONRESULTDATATYPE]);
}static UA_INLINE UA_Boolean
UA_PubSubCommunicationConfigurationResultDataType_equal(const UA_PubSubCommunicationConfigurationResultDataType *p1, const UA_PubSubCommunicationConfigurationResultDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONRESULTDATATYPE]) == UA_ORDER_EQ);
}



/* PubSubCommunicationLinkConfigurationDataType */
static UA_INLINE void
UA_PubSubCommunicationLinkConfigurationDataType_init(UA_PubSubCommunicationLinkConfigurationDataType *p) {
    memset(p, 0, sizeof(UA_PubSubCommunicationLinkConfigurationDataType));
}

static UA_INLINE UA_PubSubCommunicationLinkConfigurationDataType *
UA_PubSubCommunicationLinkConfigurationDataType_new(void) {
    return (UA_PubSubCommunicationLinkConfigurationDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONLINKCONFIGURATIONDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_PubSubCommunicationLinkConfigurationDataType_copy(const UA_PubSubCommunicationLinkConfigurationDataType *src, UA_PubSubCommunicationLinkConfigurationDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONLINKCONFIGURATIONDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_PubSubCommunicationLinkConfigurationDataType_deleteMembers(UA_PubSubCommunicationLinkConfigurationDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONLINKCONFIGURATIONDATATYPE]);
}

static UA_INLINE void
UA_PubSubCommunicationLinkConfigurationDataType_clear(UA_PubSubCommunicationLinkConfigurationDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONLINKCONFIGURATIONDATATYPE]);
}

static UA_INLINE void
UA_PubSubCommunicationLinkConfigurationDataType_delete(UA_PubSubCommunicationLinkConfigurationDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONLINKCONFIGURATIONDATATYPE]);
}static UA_INLINE UA_Boolean
UA_PubSubCommunicationLinkConfigurationDataType_equal(const UA_PubSubCommunicationLinkConfigurationDataType *p1, const UA_PubSubCommunicationLinkConfigurationDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONLINKCONFIGURATIONDATATYPE]) == UA_ORDER_EQ);
}



/* NodeIdArray */
static UA_INLINE void
UA_NodeIdArray_init(UA_NodeIdArray *p) {
    memset(p, 0, sizeof(UA_NodeIdArray));
}

static UA_INLINE UA_NodeIdArray *
UA_NodeIdArray_new(void) {
    return (UA_NodeIdArray*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDARRAY]);
}

static UA_INLINE UA_StatusCode
UA_NodeIdArray_copy(const UA_NodeIdArray *src, UA_NodeIdArray *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDARRAY]);
}

UA_DEPRECATED static UA_INLINE void
UA_NodeIdArray_deleteMembers(UA_NodeIdArray *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDARRAY]);
}

static UA_INLINE void
UA_NodeIdArray_clear(UA_NodeIdArray *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDARRAY]);
}

static UA_INLINE void
UA_NodeIdArray_delete(UA_NodeIdArray *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDARRAY]);
}static UA_INLINE UA_Boolean
UA_NodeIdArray_equal(const UA_NodeIdArray *p1, const UA_NodeIdArray *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDARRAY]) == UA_ORDER_EQ);
}



/* NodeIdValuePair */
static UA_INLINE void
UA_NodeIdValuePair_init(UA_NodeIdValuePair *p) {
    memset(p, 0, sizeof(UA_NodeIdValuePair));
}

static UA_INLINE UA_NodeIdValuePair *
UA_NodeIdValuePair_new(void) {
    return (UA_NodeIdValuePair*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR]);
}

static UA_INLINE UA_StatusCode
UA_NodeIdValuePair_copy(const UA_NodeIdValuePair *src, UA_NodeIdValuePair *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR]);
}

UA_DEPRECATED static UA_INLINE void
UA_NodeIdValuePair_deleteMembers(UA_NodeIdValuePair *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR]);
}

static UA_INLINE void
UA_NodeIdValuePair_clear(UA_NodeIdValuePair *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR]);
}

static UA_INLINE void
UA_NodeIdValuePair_delete(UA_NodeIdValuePair *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR]);
}static UA_INLINE UA_Boolean
UA_NodeIdValuePair_equal(const UA_NodeIdValuePair *p1, const UA_NodeIdValuePair *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR]) == UA_ORDER_EQ);
}



/* RelatedEndpointDataType */
static UA_INLINE void
UA_RelatedEndpointDataType_init(UA_RelatedEndpointDataType *p) {
    memset(p, 0, sizeof(UA_RelatedEndpointDataType));
}

static UA_INLINE UA_RelatedEndpointDataType *
UA_RelatedEndpointDataType_new(void) {
    return (UA_RelatedEndpointDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_RELATEDENDPOINTDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_RelatedEndpointDataType_copy(const UA_RelatedEndpointDataType *src, UA_RelatedEndpointDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_RELATEDENDPOINTDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_RelatedEndpointDataType_deleteMembers(UA_RelatedEndpointDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_RELATEDENDPOINTDATATYPE]);
}

static UA_INLINE void
UA_RelatedEndpointDataType_clear(UA_RelatedEndpointDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_RELATEDENDPOINTDATATYPE]);
}

static UA_INLINE void
UA_RelatedEndpointDataType_delete(UA_RelatedEndpointDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_RELATEDENDPOINTDATATYPE]);
}static UA_INLINE UA_Boolean
UA_RelatedEndpointDataType_equal(const UA_RelatedEndpointDataType *p1, const UA_RelatedEndpointDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_RELATEDENDPOINTDATATYPE]) == UA_ORDER_EQ);
}



/* PubSubReserveCommunicationIdsDataType */
static UA_INLINE void
UA_PubSubReserveCommunicationIdsDataType_init(UA_PubSubReserveCommunicationIdsDataType *p) {
    memset(p, 0, sizeof(UA_PubSubReserveCommunicationIdsDataType));
}

static UA_INLINE UA_PubSubReserveCommunicationIdsDataType *
UA_PubSubReserveCommunicationIdsDataType_new(void) {
    return (UA_PubSubReserveCommunicationIdsDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_PubSubReserveCommunicationIdsDataType_copy(const UA_PubSubReserveCommunicationIdsDataType *src, UA_PubSubReserveCommunicationIdsDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_PubSubReserveCommunicationIdsDataType_deleteMembers(UA_PubSubReserveCommunicationIdsDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSDATATYPE]);
}

static UA_INLINE void
UA_PubSubReserveCommunicationIdsDataType_clear(UA_PubSubReserveCommunicationIdsDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSDATATYPE]);
}

static UA_INLINE void
UA_PubSubReserveCommunicationIdsDataType_delete(UA_PubSubReserveCommunicationIdsDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSDATATYPE]);
}static UA_INLINE UA_Boolean
UA_PubSubReserveCommunicationIdsDataType_equal(const UA_PubSubReserveCommunicationIdsDataType *p1, const UA_PubSubReserveCommunicationIdsDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSDATATYPE]) == UA_ORDER_EQ);
}



/* PubSubReserveCommunicationIds2DataType */
static UA_INLINE void
UA_PubSubReserveCommunicationIds2DataType_init(UA_PubSubReserveCommunicationIds2DataType *p) {
    memset(p, 0, sizeof(UA_PubSubReserveCommunicationIds2DataType));
}

static UA_INLINE UA_PubSubReserveCommunicationIds2DataType *
UA_PubSubReserveCommunicationIds2DataType_new(void) {
    return (UA_PubSubReserveCommunicationIds2DataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDS2DATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_PubSubReserveCommunicationIds2DataType_copy(const UA_PubSubReserveCommunicationIds2DataType *src, UA_PubSubReserveCommunicationIds2DataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDS2DATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_PubSubReserveCommunicationIds2DataType_deleteMembers(UA_PubSubReserveCommunicationIds2DataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDS2DATATYPE]);
}

static UA_INLINE void
UA_PubSubReserveCommunicationIds2DataType_clear(UA_PubSubReserveCommunicationIds2DataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDS2DATATYPE]);
}

static UA_INLINE void
UA_PubSubReserveCommunicationIds2DataType_delete(UA_PubSubReserveCommunicationIds2DataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDS2DATATYPE]);
}static UA_INLINE UA_Boolean
UA_PubSubReserveCommunicationIds2DataType_equal(const UA_PubSubReserveCommunicationIds2DataType *p1, const UA_PubSubReserveCommunicationIds2DataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDS2DATATYPE]) == UA_ORDER_EQ);
}



/* PubSubReserveCommunicationIdsResultDataType */
static UA_INLINE void
UA_PubSubReserveCommunicationIdsResultDataType_init(UA_PubSubReserveCommunicationIdsResultDataType *p) {
    memset(p, 0, sizeof(UA_PubSubReserveCommunicationIdsResultDataType));
}

static UA_INLINE UA_PubSubReserveCommunicationIdsResultDataType *
UA_PubSubReserveCommunicationIdsResultDataType_new(void) {
    return (UA_PubSubReserveCommunicationIdsResultDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULTDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_PubSubReserveCommunicationIdsResultDataType_copy(const UA_PubSubReserveCommunicationIdsResultDataType *src, UA_PubSubReserveCommunicationIdsResultDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULTDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_PubSubReserveCommunicationIdsResultDataType_deleteMembers(UA_PubSubReserveCommunicationIdsResultDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULTDATATYPE]);
}

static UA_INLINE void
UA_PubSubReserveCommunicationIdsResultDataType_clear(UA_PubSubReserveCommunicationIdsResultDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULTDATATYPE]);
}

static UA_INLINE void
UA_PubSubReserveCommunicationIdsResultDataType_delete(UA_PubSubReserveCommunicationIdsResultDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULTDATATYPE]);
}static UA_INLINE UA_Boolean
UA_PubSubReserveCommunicationIdsResultDataType_equal(const UA_PubSubReserveCommunicationIdsResultDataType *p1, const UA_PubSubReserveCommunicationIdsResultDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULTDATATYPE]) == UA_ORDER_EQ);
}



/* PubSubReserveCommunicationIdsResult2DataType */
static UA_INLINE void
UA_PubSubReserveCommunicationIdsResult2DataType_init(UA_PubSubReserveCommunicationIdsResult2DataType *p) {
    memset(p, 0, sizeof(UA_PubSubReserveCommunicationIdsResult2DataType));
}

static UA_INLINE UA_PubSubReserveCommunicationIdsResult2DataType *
UA_PubSubReserveCommunicationIdsResult2DataType_new(void) {
    return (UA_PubSubReserveCommunicationIdsResult2DataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULT2DATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_PubSubReserveCommunicationIdsResult2DataType_copy(const UA_PubSubReserveCommunicationIdsResult2DataType *src, UA_PubSubReserveCommunicationIdsResult2DataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULT2DATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_PubSubReserveCommunicationIdsResult2DataType_deleteMembers(UA_PubSubReserveCommunicationIdsResult2DataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULT2DATATYPE]);
}

static UA_INLINE void
UA_PubSubReserveCommunicationIdsResult2DataType_clear(UA_PubSubReserveCommunicationIdsResult2DataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULT2DATATYPE]);
}

static UA_INLINE void
UA_PubSubReserveCommunicationIdsResult2DataType_delete(UA_PubSubReserveCommunicationIdsResult2DataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULT2DATATYPE]);
}static UA_INLINE UA_Boolean
UA_PubSubReserveCommunicationIdsResult2DataType_equal(const UA_PubSubReserveCommunicationIdsResult2DataType *p1, const UA_PubSubReserveCommunicationIdsResult2DataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULT2DATATYPE]) == UA_ORDER_EQ);
}



/* ConnectionEndpointDefinitionDataType */
static UA_INLINE void
UA_ConnectionEndpointDefinitionDataType_init(UA_ConnectionEndpointDefinitionDataType *p) {
    memset(p, 0, sizeof(UA_ConnectionEndpointDefinitionDataType));
}

static UA_INLINE UA_ConnectionEndpointDefinitionDataType *
UA_ConnectionEndpointDefinitionDataType_new(void) {
    return (UA_ConnectionEndpointDefinitionDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTDEFINITIONDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_ConnectionEndpointDefinitionDataType_copy(const UA_ConnectionEndpointDefinitionDataType *src, UA_ConnectionEndpointDefinitionDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTDEFINITIONDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_ConnectionEndpointDefinitionDataType_deleteMembers(UA_ConnectionEndpointDefinitionDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTDEFINITIONDATATYPE]);
}

static UA_INLINE void
UA_ConnectionEndpointDefinitionDataType_clear(UA_ConnectionEndpointDefinitionDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTDEFINITIONDATATYPE]);
}

static UA_INLINE void
UA_ConnectionEndpointDefinitionDataType_delete(UA_ConnectionEndpointDefinitionDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTDEFINITIONDATATYPE]);
}static UA_INLINE UA_Boolean
UA_ConnectionEndpointDefinitionDataType_equal(const UA_ConnectionEndpointDefinitionDataType *p1, const UA_ConnectionEndpointDefinitionDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTDEFINITIONDATATYPE]) == UA_ORDER_EQ);
}



/* AssetVerificationModeEnum */
static UA_INLINE void
UA_AssetVerificationModeEnum_init(UA_AssetVerificationModeEnum *p) {
    memset(p, 0, sizeof(UA_AssetVerificationModeEnum));
}

static UA_INLINE UA_AssetVerificationModeEnum *
UA_AssetVerificationModeEnum_new(void) {
    return (UA_AssetVerificationModeEnum*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONMODEENUM]);
}

static UA_INLINE UA_StatusCode
UA_AssetVerificationModeEnum_copy(const UA_AssetVerificationModeEnum *src, UA_AssetVerificationModeEnum *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONMODEENUM]);
}

UA_DEPRECATED static UA_INLINE void
UA_AssetVerificationModeEnum_deleteMembers(UA_AssetVerificationModeEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONMODEENUM]);
}

static UA_INLINE void
UA_AssetVerificationModeEnum_clear(UA_AssetVerificationModeEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONMODEENUM]);
}

static UA_INLINE void
UA_AssetVerificationModeEnum_delete(UA_AssetVerificationModeEnum *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONMODEENUM]);
}static UA_INLINE UA_Boolean
UA_AssetVerificationModeEnum_equal(const UA_AssetVerificationModeEnum *p1, const UA_AssetVerificationModeEnum *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONMODEENUM]) == UA_ORDER_EQ);
}



/* AssetVerificationResultEnum */
static UA_INLINE void
UA_AssetVerificationResultEnum_init(UA_AssetVerificationResultEnum *p) {
    memset(p, 0, sizeof(UA_AssetVerificationResultEnum));
}

static UA_INLINE UA_AssetVerificationResultEnum *
UA_AssetVerificationResultEnum_new(void) {
    return (UA_AssetVerificationResultEnum*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTENUM]);
}

static UA_INLINE UA_StatusCode
UA_AssetVerificationResultEnum_copy(const UA_AssetVerificationResultEnum *src, UA_AssetVerificationResultEnum *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTENUM]);
}

UA_DEPRECATED static UA_INLINE void
UA_AssetVerificationResultEnum_deleteMembers(UA_AssetVerificationResultEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTENUM]);
}

static UA_INLINE void
UA_AssetVerificationResultEnum_clear(UA_AssetVerificationResultEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTENUM]);
}

static UA_INLINE void
UA_AssetVerificationResultEnum_delete(UA_AssetVerificationResultEnum *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTENUM]);
}static UA_INLINE UA_Boolean
UA_AssetVerificationResultEnum_equal(const UA_AssetVerificationResultEnum *p1, const UA_AssetVerificationResultEnum *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTENUM]) == UA_ORDER_EQ);
}



/* FunctionalEntityVerificationResultEnum */
static UA_INLINE void
UA_FunctionalEntityVerificationResultEnum_init(UA_FunctionalEntityVerificationResultEnum *p) {
    memset(p, 0, sizeof(UA_FunctionalEntityVerificationResultEnum));
}

static UA_INLINE UA_FunctionalEntityVerificationResultEnum *
UA_FunctionalEntityVerificationResultEnum_new(void) {
    return (UA_FunctionalEntityVerificationResultEnum*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FUNCTIONALENTITYVERIFICATIONRESULTENUM]);
}

static UA_INLINE UA_StatusCode
UA_FunctionalEntityVerificationResultEnum_copy(const UA_FunctionalEntityVerificationResultEnum *src, UA_FunctionalEntityVerificationResultEnum *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FUNCTIONALENTITYVERIFICATIONRESULTENUM]);
}

UA_DEPRECATED static UA_INLINE void
UA_FunctionalEntityVerificationResultEnum_deleteMembers(UA_FunctionalEntityVerificationResultEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FUNCTIONALENTITYVERIFICATIONRESULTENUM]);
}

static UA_INLINE void
UA_FunctionalEntityVerificationResultEnum_clear(UA_FunctionalEntityVerificationResultEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FUNCTIONALENTITYVERIFICATIONRESULTENUM]);
}

static UA_INLINE void
UA_FunctionalEntityVerificationResultEnum_delete(UA_FunctionalEntityVerificationResultEnum *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FUNCTIONALENTITYVERIFICATIONRESULTENUM]);
}static UA_INLINE UA_Boolean
UA_FunctionalEntityVerificationResultEnum_equal(const UA_FunctionalEntityVerificationResultEnum *p1, const UA_FunctionalEntityVerificationResultEnum *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FUNCTIONALENTITYVERIFICATIONRESULTENUM]) == UA_ORDER_EQ);
}



/* PubSubConnectionEndpointModeEnum */
static UA_INLINE void
UA_PubSubConnectionEndpointModeEnum_init(UA_PubSubConnectionEndpointModeEnum *p) {
    memset(p, 0, sizeof(UA_PubSubConnectionEndpointModeEnum));
}

static UA_INLINE UA_PubSubConnectionEndpointModeEnum *
UA_PubSubConnectionEndpointModeEnum_new(void) {
    return (UA_PubSubConnectionEndpointModeEnum*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTMODEENUM]);
}

static UA_INLINE UA_StatusCode
UA_PubSubConnectionEndpointModeEnum_copy(const UA_PubSubConnectionEndpointModeEnum *src, UA_PubSubConnectionEndpointModeEnum *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTMODEENUM]);
}

UA_DEPRECATED static UA_INLINE void
UA_PubSubConnectionEndpointModeEnum_deleteMembers(UA_PubSubConnectionEndpointModeEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTMODEENUM]);
}

static UA_INLINE void
UA_PubSubConnectionEndpointModeEnum_clear(UA_PubSubConnectionEndpointModeEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTMODEENUM]);
}

static UA_INLINE void
UA_PubSubConnectionEndpointModeEnum_delete(UA_PubSubConnectionEndpointModeEnum *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTMODEENUM]);
}static UA_INLINE UA_Boolean
UA_PubSubConnectionEndpointModeEnum_equal(const UA_PubSubConnectionEndpointModeEnum *p1, const UA_PubSubConnectionEndpointModeEnum *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTMODEENUM]) == UA_ORDER_EQ);
}



/* FxCommandMask */
static UA_INLINE void
UA_FxCommandMask_init(UA_FxCommandMask *p) {
    memset(p, 0, sizeof(UA_FxCommandMask));
}

static UA_INLINE UA_FxCommandMask *
UA_FxCommandMask_new(void) {
    return (UA_FxCommandMask*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FXCOMMANDMASK]);
}

static UA_INLINE UA_StatusCode
UA_FxCommandMask_copy(const UA_FxCommandMask *src, UA_FxCommandMask *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FXCOMMANDMASK]);
}

UA_DEPRECATED static UA_INLINE void
UA_FxCommandMask_deleteMembers(UA_FxCommandMask *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FXCOMMANDMASK]);
}

static UA_INLINE void
UA_FxCommandMask_clear(UA_FxCommandMask *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FXCOMMANDMASK]);
}

static UA_INLINE void
UA_FxCommandMask_delete(UA_FxCommandMask *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FXCOMMANDMASK]);
}static UA_INLINE UA_Boolean
UA_FxCommandMask_equal(const UA_FxCommandMask *p1, const UA_FxCommandMask *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FXCOMMANDMASK]) == UA_ORDER_EQ);
}



/* AssetVerificationDataType */
static UA_INLINE void
UA_AssetVerificationDataType_init(UA_AssetVerificationDataType *p) {
    memset(p, 0, sizeof(UA_AssetVerificationDataType));
}

static UA_INLINE UA_AssetVerificationDataType *
UA_AssetVerificationDataType_new(void) {
    return (UA_AssetVerificationDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_AssetVerificationDataType_copy(const UA_AssetVerificationDataType *src, UA_AssetVerificationDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_AssetVerificationDataType_deleteMembers(UA_AssetVerificationDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONDATATYPE]);
}

static UA_INLINE void
UA_AssetVerificationDataType_clear(UA_AssetVerificationDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONDATATYPE]);
}

static UA_INLINE void
UA_AssetVerificationDataType_delete(UA_AssetVerificationDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONDATATYPE]);
}static UA_INLINE UA_Boolean
UA_AssetVerificationDataType_equal(const UA_AssetVerificationDataType *p1, const UA_AssetVerificationDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONDATATYPE]) == UA_ORDER_EQ);
}



/* AssetVerificationResultDataType */
static UA_INLINE void
UA_AssetVerificationResultDataType_init(UA_AssetVerificationResultDataType *p) {
    memset(p, 0, sizeof(UA_AssetVerificationResultDataType));
}

static UA_INLINE UA_AssetVerificationResultDataType *
UA_AssetVerificationResultDataType_new(void) {
    return (UA_AssetVerificationResultDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_AssetVerificationResultDataType_copy(const UA_AssetVerificationResultDataType *src, UA_AssetVerificationResultDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_AssetVerificationResultDataType_deleteMembers(UA_AssetVerificationResultDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTDATATYPE]);
}

static UA_INLINE void
UA_AssetVerificationResultDataType_clear(UA_AssetVerificationResultDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTDATATYPE]);
}

static UA_INLINE void
UA_AssetVerificationResultDataType_delete(UA_AssetVerificationResultDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTDATATYPE]);
}static UA_INLINE UA_Boolean
UA_AssetVerificationResultDataType_equal(const UA_AssetVerificationResultDataType *p1, const UA_AssetVerificationResultDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTDATATYPE]) == UA_ORDER_EQ);
}



/* ConnectionEndpointConfigurationDataType */
static UA_INLINE void
UA_ConnectionEndpointConfigurationDataType_init(UA_ConnectionEndpointConfigurationDataType *p) {
    memset(p, 0, sizeof(UA_ConnectionEndpointConfigurationDataType));
}

static UA_INLINE UA_ConnectionEndpointConfigurationDataType *
UA_ConnectionEndpointConfigurationDataType_new(void) {
    return (UA_ConnectionEndpointConfigurationDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_ConnectionEndpointConfigurationDataType_copy(const UA_ConnectionEndpointConfigurationDataType *src, UA_ConnectionEndpointConfigurationDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_ConnectionEndpointConfigurationDataType_deleteMembers(UA_ConnectionEndpointConfigurationDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONDATATYPE]);
}

static UA_INLINE void
UA_ConnectionEndpointConfigurationDataType_clear(UA_ConnectionEndpointConfigurationDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONDATATYPE]);
}

static UA_INLINE void
UA_ConnectionEndpointConfigurationDataType_delete(UA_ConnectionEndpointConfigurationDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONDATATYPE]);
}static UA_INLINE UA_Boolean
UA_ConnectionEndpointConfigurationDataType_equal(const UA_ConnectionEndpointConfigurationDataType *p1, const UA_ConnectionEndpointConfigurationDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONDATATYPE]) == UA_ORDER_EQ);
}



/* ConnectionEndpointConfigurationResultDataType */
static UA_INLINE void
UA_ConnectionEndpointConfigurationResultDataType_init(UA_ConnectionEndpointConfigurationResultDataType *p) {
    memset(p, 0, sizeof(UA_ConnectionEndpointConfigurationResultDataType));
}

static UA_INLINE UA_ConnectionEndpointConfigurationResultDataType *
UA_ConnectionEndpointConfigurationResultDataType_new(void) {
    return (UA_ConnectionEndpointConfigurationResultDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONRESULTDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_ConnectionEndpointConfigurationResultDataType_copy(const UA_ConnectionEndpointConfigurationResultDataType *src, UA_ConnectionEndpointConfigurationResultDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONRESULTDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_ConnectionEndpointConfigurationResultDataType_deleteMembers(UA_ConnectionEndpointConfigurationResultDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONRESULTDATATYPE]);
}

static UA_INLINE void
UA_ConnectionEndpointConfigurationResultDataType_clear(UA_ConnectionEndpointConfigurationResultDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONRESULTDATATYPE]);
}

static UA_INLINE void
UA_ConnectionEndpointConfigurationResultDataType_delete(UA_ConnectionEndpointConfigurationResultDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONRESULTDATATYPE]);
}static UA_INLINE UA_Boolean
UA_ConnectionEndpointConfigurationResultDataType_equal(const UA_ConnectionEndpointConfigurationResultDataType *p1, const UA_ConnectionEndpointConfigurationResultDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONRESULTDATATYPE]) == UA_ORDER_EQ);
}



/* ConnectionEndpointParameterDataType */
static UA_INLINE void
UA_ConnectionEndpointParameterDataType_init(UA_ConnectionEndpointParameterDataType *p) {
    memset(p, 0, sizeof(UA_ConnectionEndpointParameterDataType));
}

static UA_INLINE UA_ConnectionEndpointParameterDataType *
UA_ConnectionEndpointParameterDataType_new(void) {
    return (UA_ConnectionEndpointParameterDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTPARAMETERDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_ConnectionEndpointParameterDataType_copy(const UA_ConnectionEndpointParameterDataType *src, UA_ConnectionEndpointParameterDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTPARAMETERDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_ConnectionEndpointParameterDataType_deleteMembers(UA_ConnectionEndpointParameterDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTPARAMETERDATATYPE]);
}

static UA_INLINE void
UA_ConnectionEndpointParameterDataType_clear(UA_ConnectionEndpointParameterDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTPARAMETERDATATYPE]);
}

static UA_INLINE void
UA_ConnectionEndpointParameterDataType_delete(UA_ConnectionEndpointParameterDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTPARAMETERDATATYPE]);
}static UA_INLINE UA_Boolean
UA_ConnectionEndpointParameterDataType_equal(const UA_ConnectionEndpointParameterDataType *p1, const UA_ConnectionEndpointParameterDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTPARAMETERDATATYPE]) == UA_ORDER_EQ);
}



/* PubSubConnectionEndpointParameterDataType */
static UA_INLINE void
UA_PubSubConnectionEndpointParameterDataType_init(UA_PubSubConnectionEndpointParameterDataType *p) {
    memset(p, 0, sizeof(UA_PubSubConnectionEndpointParameterDataType));
}

static UA_INLINE UA_PubSubConnectionEndpointParameterDataType *
UA_PubSubConnectionEndpointParameterDataType_new(void) {
    return (UA_PubSubConnectionEndpointParameterDataType*)UA_new(&UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTPARAMETERDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_PubSubConnectionEndpointParameterDataType_copy(const UA_PubSubConnectionEndpointParameterDataType *src, UA_PubSubConnectionEndpointParameterDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTPARAMETERDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_PubSubConnectionEndpointParameterDataType_deleteMembers(UA_PubSubConnectionEndpointParameterDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTPARAMETERDATATYPE]);
}

static UA_INLINE void
UA_PubSubConnectionEndpointParameterDataType_clear(UA_PubSubConnectionEndpointParameterDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTPARAMETERDATATYPE]);
}

static UA_INLINE void
UA_PubSubConnectionEndpointParameterDataType_delete(UA_PubSubConnectionEndpointParameterDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTPARAMETERDATATYPE]);
}static UA_INLINE UA_Boolean
UA_PubSubConnectionEndpointParameterDataType_equal(const UA_PubSubConnectionEndpointParameterDataType *p1, const UA_PubSubConnectionEndpointParameterDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTPARAMETERDATATYPE]) == UA_ORDER_EQ);
}



#if defined(__GNUC__) && __GNUC__ >= 4 && __GNUC_MINOR__ >= 6
# pragma GCC diagnostic pop
#endif

_UA_END_DECLS

#endif /* TYPES_UAFX_DATA_GENERATED_HANDLING_H_ */
