/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#include "types_uafx_data_generated.h"

/* PubSubCommunicationConfigurationDataType */
static UA_DataTypeMember PubSubCommunicationConfigurationDataType_members[3] = {
{
    UA_TYPENAME("PubSubConfiguration") /* .memberName */
    &UA_TYPES[UA_TYPES_PUBSUBCONFIGURATION2DATATYPE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("RequireCompleteUpdate") /* .memberName */
    &UA_TYPES[UA_TYPES_BOOLEAN], /* .memberType */
    offsetof(UA_PubSubCommunicationConfigurationDataType, requireCompleteUpdate) - offsetof(UA_PubSubCommunicationConfigurationDataType, pubSubConfiguration) - sizeof(UA_PubSubConfiguration2DataType), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConfigurationReferences") /* .memberName */
    &UA_TYPES[UA_TYPES_PUBSUBCONFIGURATIONREFDATATYPE], /* .memberType */
    offsetof(UA_PubSubCommunicationConfigurationDataType, configurationReferencesSize) - offsetof(UA_PubSubCommunicationConfigurationDataType, requireCompleteUpdate) - sizeof(UA_Boolean), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};

/* PubSubCommunicationConfigurationResultDataType */
static UA_DataTypeMember PubSubCommunicationConfigurationResultDataType_members[5] = {
{
    UA_TYPENAME("Result") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ChangesApplied") /* .memberName */
    &UA_TYPES[UA_TYPES_BOOLEAN], /* .memberType */
    offsetof(UA_PubSubCommunicationConfigurationResultDataType, changesApplied) - offsetof(UA_PubSubCommunicationConfigurationResultDataType, result) - sizeof(UA_StatusCode), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ReferenceResults") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_PubSubCommunicationConfigurationResultDataType, referenceResultsSize) - offsetof(UA_PubSubCommunicationConfigurationResultDataType, changesApplied) - sizeof(UA_Boolean), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConfigurationValues") /* .memberName */
    &UA_TYPES[UA_TYPES_PUBSUBCONFIGURATIONVALUEDATATYPE], /* .memberType */
    offsetof(UA_PubSubCommunicationConfigurationResultDataType, configurationValuesSize) - offsetof(UA_PubSubCommunicationConfigurationResultDataType, referenceResults) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConfigurationObjects") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    offsetof(UA_PubSubCommunicationConfigurationResultDataType, configurationObjectsSize) - offsetof(UA_PubSubCommunicationConfigurationResultDataType, configurationValues) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};

/* PubSubCommunicationLinkConfigurationDataType */
static UA_DataTypeMember PubSubCommunicationLinkConfigurationDataType_members[4] = {
{
    UA_TYPENAME("DataSetReaderRef") /* .memberName */
    &UA_TYPES[UA_TYPES_PUBSUBCONFIGURATIONREFDATATYPE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ExpectedSubscribedDataSetVersion") /* .memberName */
    &UA_TYPES[UA_TYPES_CONFIGURATIONVERSIONDATATYPE], /* .memberType */
    offsetof(UA_PubSubCommunicationLinkConfigurationDataType, expectedSubscribedDataSetVersion) - offsetof(UA_PubSubCommunicationLinkConfigurationDataType, dataSetReaderRef) - sizeof(UA_PubSubConfigurationRefDataType), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("DataSetWriterRef") /* .memberName */
    &UA_TYPES[UA_TYPES_PUBSUBCONFIGURATIONREFDATATYPE], /* .memberType */
    offsetof(UA_PubSubCommunicationLinkConfigurationDataType, dataSetWriterRef) - offsetof(UA_PubSubCommunicationLinkConfigurationDataType, expectedSubscribedDataSetVersion) - sizeof(UA_ConfigurationVersionDataType), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ExpectedPublishedDataSetVersion") /* .memberName */
    &UA_TYPES[UA_TYPES_CONFIGURATIONVERSIONDATATYPE], /* .memberType */
    offsetof(UA_PubSubCommunicationLinkConfigurationDataType, expectedPublishedDataSetVersion) - offsetof(UA_PubSubCommunicationLinkConfigurationDataType, dataSetWriterRef) - sizeof(UA_PubSubConfigurationRefDataType), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* NodeIdArray */
static UA_DataTypeMember NodeIdArray_members[2] = {
{
    UA_TYPENAME("Node") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ArrayIndex") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT32], /* .memberType */
    offsetof(UA_NodeIdArray, arrayIndexSize) - offsetof(UA_NodeIdArray, node) - sizeof(UA_NodeId), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};

/* NodeIdValuePair */
static UA_DataTypeMember NodeIdValuePair_members[2] = {
{
    UA_TYPENAME("Key") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDARRAY], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Value") /* .memberName */
    &UA_TYPES[UA_TYPES_VARIANT], /* .memberType */
    offsetof(UA_NodeIdValuePair, value) - offsetof(UA_NodeIdValuePair, key) - sizeof(UA_NodeIdArray), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* RelatedEndpointDataType */
static UA_DataTypeMember RelatedEndpointDataType_members[3] = {
{
    UA_TYPENAME("Address") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConnectionEndpointPath") /* .memberName */
    &UA_TYPES[UA_TYPES_PORTABLEQUALIFIEDNAME], /* .memberType */
    offsetof(UA_RelatedEndpointDataType, connectionEndpointPathSize) - offsetof(UA_RelatedEndpointDataType, address) - sizeof(UA_String), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConnectionEndpointName") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    offsetof(UA_RelatedEndpointDataType, connectionEndpointName) - offsetof(UA_RelatedEndpointDataType, connectionEndpointPath) - sizeof(void *), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PubSubReserveCommunicationIdsDataType */
static UA_DataTypeMember PubSubReserveCommunicationIdsDataType_members[3] = {
{
    UA_TYPENAME("TransportProfileUri") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("NumReqWriterGroupIds") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIdsDataType, numReqWriterGroupIds) - offsetof(UA_PubSubReserveCommunicationIdsDataType, transportProfileUri) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("NumReqDataSetWriterIds") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIdsDataType, numReqDataSetWriterIds) - offsetof(UA_PubSubReserveCommunicationIdsDataType, numReqWriterGroupIds) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PubSubReserveCommunicationIds2DataType */
static UA_DataTypeMember PubSubReserveCommunicationIds2DataType_members[4] = {
{
    UA_TYPENAME("TransportProfileUri") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("NumReqWriterGroupIds") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIds2DataType, numReqWriterGroupIds) - offsetof(UA_PubSubReserveCommunicationIds2DataType, transportProfileUri) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("NumReqDataSetWriterIds") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIds2DataType, numReqDataSetWriterIds) - offsetof(UA_PubSubReserveCommunicationIds2DataType, numReqWriterGroupIds) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("RequestTransportSpecificInfo") /* .memberName */
    &UA_TYPES[UA_TYPES_BOOLEAN], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIds2DataType, requestTransportSpecificInfo) - offsetof(UA_PubSubReserveCommunicationIds2DataType, numReqDataSetWriterIds) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PubSubReserveCommunicationIdsResultDataType */
static UA_DataTypeMember PubSubReserveCommunicationIdsResultDataType_members[4] = {
{
    UA_TYPENAME("Result") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("DefaultPublisherId") /* .memberName */
    &UA_TYPES[UA_TYPES_VARIANT], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIdsResultDataType, defaultPublisherId) - offsetof(UA_PubSubReserveCommunicationIdsResultDataType, result) - sizeof(UA_StatusCode), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("WriterGroupIds") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIdsResultDataType, writerGroupIdsSize) - offsetof(UA_PubSubReserveCommunicationIdsResultDataType, defaultPublisherId) - sizeof(UA_Variant), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("DataSetWriterIds") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIdsResultDataType, dataSetWriterIdsSize) - offsetof(UA_PubSubReserveCommunicationIdsResultDataType, writerGroupIds) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};

/* PubSubReserveCommunicationIdsResult2DataType */
static UA_DataTypeMember PubSubReserveCommunicationIdsResult2DataType_members[5] = {
{
    UA_TYPENAME("Result") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("DefaultPublisherId") /* .memberName */
    &UA_TYPES[UA_TYPES_VARIANT], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIdsResult2DataType, defaultPublisherId) - offsetof(UA_PubSubReserveCommunicationIdsResult2DataType, result) - sizeof(UA_StatusCode), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("WriterGroupIds") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIdsResult2DataType, writerGroupIdsSize) - offsetof(UA_PubSubReserveCommunicationIdsResult2DataType, defaultPublisherId) - sizeof(UA_Variant), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("DataSetWriterIds") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIdsResult2DataType, dataSetWriterIdsSize) - offsetof(UA_PubSubReserveCommunicationIdsResult2DataType, writerGroupIds) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("TransportSpecificInfo") /* .memberName */
    &UA_TYPES[UA_TYPES_VARIANT], /* .memberType */
    offsetof(UA_PubSubReserveCommunicationIdsResult2DataType, transportSpecificInfo) - offsetof(UA_PubSubReserveCommunicationIdsResult2DataType, dataSetWriterIds) - sizeof(void *), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* ConnectionEndpointDefinitionDataType */
static UA_DataTypeMember ConnectionEndpointDefinitionDataType_members[2] = {
{
    UA_TYPENAME("Parameter") /* .memberName */
    &UA_TYPES[UA_TYPES_EXTENSIONOBJECT], /* .memberType */
    offsetof(UA_ConnectionEndpointDefinitionDataType, fields.parameter), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Node") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    offsetof(UA_ConnectionEndpointDefinitionDataType, fields.node), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* AssetVerificationModeEnum */
#define AssetVerificationModeEnum_members NULL

/* AssetVerificationResultEnum */
#define AssetVerificationResultEnum_members NULL

/* FunctionalEntityVerificationResultEnum */
#define FunctionalEntityVerificationResultEnum_members NULL

/* PubSubConnectionEndpointModeEnum */
#define PubSubConnectionEndpointModeEnum_members NULL

/* FxCommandMask */
#define FxCommandMask_members NULL

/* AssetVerificationDataType */
static UA_DataTypeMember AssetVerificationDataType_members[5] = {
{
    UA_TYPENAME("AssetToVerify") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("VerificationMode") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONMODEENUM], /* .memberType */
    offsetof(UA_AssetVerificationDataType, verificationMode) - offsetof(UA_AssetVerificationDataType, assetToVerify) - sizeof(UA_NodeId), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ExpectedVerificationResult") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTENUM], /* .memberType */
    offsetof(UA_AssetVerificationDataType, expectedVerificationResult) - offsetof(UA_AssetVerificationDataType, verificationMode) - sizeof(UA_AssetVerificationModeEnum), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ExpectedVerificationVariables") /* .memberName */
    &UA_TYPES[UA_TYPES_KEYVALUEPAIR], /* .memberType */
    offsetof(UA_AssetVerificationDataType, expectedVerificationVariablesSize) - offsetof(UA_AssetVerificationDataType, expectedVerificationResult) - sizeof(UA_AssetVerificationResultEnum), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ExpectedAdditionalVerificationVariables") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR], /* .memberType */
    offsetof(UA_AssetVerificationDataType, expectedAdditionalVerificationVariablesSize) - offsetof(UA_AssetVerificationDataType, expectedVerificationVariables) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};

/* AssetVerificationResultDataType */
static UA_DataTypeMember AssetVerificationResultDataType_members[4] = {
{
    UA_TYPENAME("VerificationStatus") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("VerificationResult") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTENUM], /* .memberType */
    offsetof(UA_AssetVerificationResultDataType, verificationResult) - offsetof(UA_AssetVerificationResultDataType, verificationStatus) - sizeof(UA_StatusCode), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("VerificationVariablesErrors") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_AssetVerificationResultDataType, verificationVariablesErrorsSize) - offsetof(UA_AssetVerificationResultDataType, verificationResult) - sizeof(UA_AssetVerificationResultEnum), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("VerificationAdditionalVariablesErrors") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_AssetVerificationResultDataType, verificationAdditionalVariablesErrorsSize) - offsetof(UA_AssetVerificationResultDataType, verificationVariablesErrors) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};

/* ConnectionEndpointConfigurationDataType */
static UA_DataTypeMember ConnectionEndpointConfigurationDataType_members[6] = {
{
    UA_TYPENAME("FunctionalEntityNode") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConnectionEndpoint") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTDEFINITIONDATATYPE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationDataType, connectionEndpoint) - offsetof(UA_ConnectionEndpointConfigurationDataType, functionalEntityNode) - sizeof(UA_NodeId), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ExpectedVerificationVariables") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationDataType, expectedVerificationVariablesSize) - offsetof(UA_ConnectionEndpointConfigurationDataType, connectionEndpoint) - sizeof(UA_ConnectionEndpointDefinitionDataType), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ControlGroups") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationDataType, controlGroupsSize) - offsetof(UA_ConnectionEndpointConfigurationDataType, expectedVerificationVariables) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConfigurationData") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationDataType, configurationDataSize) - offsetof(UA_ConnectionEndpointConfigurationDataType, controlGroups) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("CommunicationLinks") /* .memberName */
    &UA_TYPES[UA_TYPES_EXTENSIONOBJECT], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationDataType, communicationLinks) - offsetof(UA_ConnectionEndpointConfigurationDataType, configurationData) - sizeof(void *), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* ConnectionEndpointConfigurationResultDataType */
static UA_DataTypeMember ConnectionEndpointConfigurationResultDataType_members[11] = {
{
    UA_TYPENAME("ConnectionEndpointId") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("FunctionalEntityNodeResult") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, functionalEntityNodeResult) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, connectionEndpointId) - sizeof(UA_NodeId), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConnectionEndpointResult") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, connectionEndpointResult) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, functionalEntityNodeResult) - sizeof(UA_StatusCode), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("VerificationResult") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_FUNCTIONALENTITYVERIFICATIONRESULTENUM], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, verificationResult) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, connectionEndpointResult) - sizeof(UA_StatusCode), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("VerificationStatus") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, verificationStatus) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, verificationResult) - sizeof(UA_FunctionalEntityVerificationResultEnum), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("VerificationVariablesErrors") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, verificationVariablesErrorsSize) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, verificationStatus) - sizeof(UA_StatusCode), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("EstablishControlResult") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, establishControlResultSize) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, verificationVariablesErrors) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConfigurationDataResult") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, configurationDataResultSize) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, establishControlResult) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ReassignControlResult") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, reassignControlResultSize) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, configurationDataResult) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("CommunicationLinksResult") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, communicationLinksResult) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, reassignControlResult) - sizeof(void *), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("EnableCommunicationResult") /* .memberName */
    &UA_TYPES[UA_TYPES_STATUSCODE], /* .memberType */
    offsetof(UA_ConnectionEndpointConfigurationResultDataType, enableCommunicationResult) - offsetof(UA_ConnectionEndpointConfigurationResultDataType, communicationLinksResult) - sizeof(UA_StatusCode), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* ConnectionEndpointParameterDataType */
static UA_DataTypeMember ConnectionEndpointParameterDataType_members[8] = {
{
    UA_TYPENAME("Name") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConnectionEndpointTypeId") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    offsetof(UA_ConnectionEndpointParameterDataType, connectionEndpointTypeId) - offsetof(UA_ConnectionEndpointParameterDataType, name) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("InputVariableIds") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    offsetof(UA_ConnectionEndpointParameterDataType, inputVariableIdsSize) - offsetof(UA_ConnectionEndpointParameterDataType, connectionEndpointTypeId) - sizeof(UA_NodeId), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("OutputVariableIds") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    offsetof(UA_ConnectionEndpointParameterDataType, outputVariableIdsSize) - offsetof(UA_ConnectionEndpointParameterDataType, inputVariableIds) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("IsPersistent") /* .memberName */
    &UA_TYPES[UA_TYPES_BOOLEAN], /* .memberType */
    offsetof(UA_ConnectionEndpointParameterDataType, isPersistent) - offsetof(UA_ConnectionEndpointParameterDataType, outputVariableIds) - sizeof(void *), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("CleanupTimeout") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_ConnectionEndpointParameterDataType, cleanupTimeout) - offsetof(UA_ConnectionEndpointParameterDataType, isPersistent) - sizeof(UA_Boolean), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("RelatedEndpoint") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_RELATEDENDPOINTDATATYPE], /* .memberType */
    offsetof(UA_ConnectionEndpointParameterDataType, relatedEndpoint) - offsetof(UA_ConnectionEndpointParameterDataType, cleanupTimeout) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("IsPreconfigured") /* .memberName */
    &UA_TYPES[UA_TYPES_BOOLEAN], /* .memberType */
    offsetof(UA_ConnectionEndpointParameterDataType, isPreconfigured) - offsetof(UA_ConnectionEndpointParameterDataType, relatedEndpoint) - sizeof(UA_RelatedEndpointDataType), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PubSubConnectionEndpointParameterDataType */
static UA_DataTypeMember PubSubConnectionEndpointParameterDataType_members[9] = {
{
    UA_TYPENAME("Name") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ConnectionEndpointTypeId") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    offsetof(UA_PubSubConnectionEndpointParameterDataType, connectionEndpointTypeId) - offsetof(UA_PubSubConnectionEndpointParameterDataType, name) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("InputVariableIds") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    offsetof(UA_PubSubConnectionEndpointParameterDataType, inputVariableIdsSize) - offsetof(UA_PubSubConnectionEndpointParameterDataType, connectionEndpointTypeId) - sizeof(UA_NodeId), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("OutputVariableIds") /* .memberName */
    &UA_TYPES[UA_TYPES_NODEID], /* .memberType */
    offsetof(UA_PubSubConnectionEndpointParameterDataType, outputVariableIdsSize) - offsetof(UA_PubSubConnectionEndpointParameterDataType, inputVariableIds) - sizeof(void *), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("IsPersistent") /* .memberName */
    &UA_TYPES[UA_TYPES_BOOLEAN], /* .memberType */
    offsetof(UA_PubSubConnectionEndpointParameterDataType, isPersistent) - offsetof(UA_PubSubConnectionEndpointParameterDataType, outputVariableIds) - sizeof(void *), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("CleanupTimeout") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_PubSubConnectionEndpointParameterDataType, cleanupTimeout) - offsetof(UA_PubSubConnectionEndpointParameterDataType, isPersistent) - sizeof(UA_Boolean), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("RelatedEndpoint") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_RELATEDENDPOINTDATATYPE], /* .memberType */
    offsetof(UA_PubSubConnectionEndpointParameterDataType, relatedEndpoint) - offsetof(UA_PubSubConnectionEndpointParameterDataType, cleanupTimeout) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("IsPreconfigured") /* .memberName */
    &UA_TYPES[UA_TYPES_BOOLEAN], /* .memberType */
    offsetof(UA_PubSubConnectionEndpointParameterDataType, isPreconfigured) - offsetof(UA_PubSubConnectionEndpointParameterDataType, relatedEndpoint) - sizeof(UA_RelatedEndpointDataType), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Mode") /* .memberName */
    &UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTMODEENUM], /* .memberType */
    offsetof(UA_PubSubConnectionEndpointParameterDataType, mode) - offsetof(UA_PubSubConnectionEndpointParameterDataType, isPreconfigured) - sizeof(UA_Boolean), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};
UA_DataType UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_COUNT] = {
/* PubSubCommunicationConfigurationDataType */
{
    UA_TYPENAME("PubSubCommunicationConfigurationDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1045LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {1144LU}}, /* .binaryEncodingId */
    sizeof(UA_PubSubCommunicationConfigurationDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    3, /* .membersSize */
    PubSubCommunicationConfigurationDataType_members  /* .members */
},
/* PubSubCommunicationConfigurationResultDataType */
{
    UA_TYPENAME("PubSubCommunicationConfigurationResultDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1039LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {1208LU}}, /* .binaryEncodingId */
    sizeof(UA_PubSubCommunicationConfigurationResultDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    5, /* .membersSize */
    PubSubCommunicationConfigurationResultDataType_members  /* .members */
},
/* PubSubCommunicationLinkConfigurationDataType */
{
    UA_TYPENAME("PubSubCommunicationLinkConfigurationDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1031LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {1102LU}}, /* .binaryEncodingId */
    sizeof(UA_PubSubCommunicationLinkConfigurationDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    true, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    PubSubCommunicationLinkConfigurationDataType_members  /* .members */
},
/* NodeIdArray */
{
    UA_TYPENAME("NodeIdArray") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1034LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {1111LU}}, /* .binaryEncodingId */
    sizeof(UA_NodeIdArray), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    NodeIdArray_members  /* .members */
},
/* NodeIdValuePair */
{
    UA_TYPENAME("NodeIdValuePair") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1028LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {1093LU}}, /* .binaryEncodingId */
    sizeof(UA_NodeIdValuePair), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    NodeIdValuePair_members  /* .members */
},
/* RelatedEndpointDataType */
{
    UA_TYPENAME("RelatedEndpointDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3003LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5001LU}}, /* .binaryEncodingId */
    sizeof(UA_RelatedEndpointDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    3, /* .membersSize */
    RelatedEndpointDataType_members  /* .members */
},
/* PubSubReserveCommunicationIdsDataType */
{
    UA_TYPENAME("PubSubReserveCommunicationIdsDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3018LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5082LU}}, /* .binaryEncodingId */
    sizeof(UA_PubSubReserveCommunicationIdsDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    3, /* .membersSize */
    PubSubReserveCommunicationIdsDataType_members  /* .members */
},
/* PubSubReserveCommunicationIds2DataType */
{
    UA_TYPENAME("PubSubReserveCommunicationIds2DataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3005LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5004LU}}, /* .binaryEncodingId */
    sizeof(UA_PubSubReserveCommunicationIds2DataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    PubSubReserveCommunicationIds2DataType_members  /* .members */
},
/* PubSubReserveCommunicationIdsResultDataType */
{
    UA_TYPENAME("PubSubReserveCommunicationIdsResultDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3020LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5088LU}}, /* .binaryEncodingId */
    sizeof(UA_PubSubReserveCommunicationIdsResultDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    PubSubReserveCommunicationIdsResultDataType_members  /* .members */
},
/* PubSubReserveCommunicationIdsResult2DataType */
{
    UA_TYPENAME("PubSubReserveCommunicationIdsResult2DataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3013LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5007LU}}, /* .binaryEncodingId */
    sizeof(UA_PubSubReserveCommunicationIdsResult2DataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    5, /* .membersSize */
    PubSubReserveCommunicationIdsResult2DataType_members  /* .members */
},
/* ConnectionEndpointDefinitionDataType */
{
    UA_TYPENAME("ConnectionEndpointDefinitionDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3011LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5054LU}}, /* .binaryEncodingId */
    sizeof(UA_ConnectionEndpointDefinitionDataType), /* .memSize */
    UA_DATATYPEKIND_UNION, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    ConnectionEndpointDefinitionDataType_members  /* .members */
},
/* AssetVerificationModeEnum */
{
    UA_TYPENAME("AssetVerificationModeEnum") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1029LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_AssetVerificationModeEnum), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    AssetVerificationModeEnum_members  /* .members */
},
/* AssetVerificationResultEnum */
{
    UA_TYPENAME("AssetVerificationResultEnum") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1037LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_AssetVerificationResultEnum), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    AssetVerificationResultEnum_members  /* .members */
},
/* FunctionalEntityVerificationResultEnum */
{
    UA_TYPENAME("FunctionalEntityVerificationResultEnum") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3002LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_FunctionalEntityVerificationResultEnum), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    FunctionalEntityVerificationResultEnum_members  /* .members */
},
/* PubSubConnectionEndpointModeEnum */
{
    UA_TYPENAME("PubSubConnectionEndpointModeEnum") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {31LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_PubSubConnectionEndpointModeEnum), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    PubSubConnectionEndpointModeEnum_members  /* .members */
},
/* FxCommandMask */
{
    UA_TYPENAME("FxCommandMask") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1024LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_FxCommandMask), /* .memSize */
    UA_DATATYPEKIND_UINT32, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    FxCommandMask_members  /* .members */
},
/* AssetVerificationDataType */
{
    UA_TYPENAME("AssetVerificationDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1048LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {1153LU}}, /* .binaryEncodingId */
    sizeof(UA_AssetVerificationDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    5, /* .membersSize */
    AssetVerificationDataType_members  /* .members */
},
/* AssetVerificationResultDataType */
{
    UA_TYPENAME("AssetVerificationResultDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1038LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {1205LU}}, /* .binaryEncodingId */
    sizeof(UA_AssetVerificationResultDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    AssetVerificationResultDataType_members  /* .members */
},
/* ConnectionEndpointConfigurationDataType */
{
    UA_TYPENAME("ConnectionEndpointConfigurationDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {1044LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {1141LU}}, /* .binaryEncodingId */
    sizeof(UA_ConnectionEndpointConfigurationDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    6, /* .membersSize */
    ConnectionEndpointConfigurationDataType_members  /* .members */
},
/* ConnectionEndpointConfigurationResultDataType */
{
    UA_TYPENAME("ConnectionEndpointConfigurationResultDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3008LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5036LU}}, /* .binaryEncodingId */
    sizeof(UA_ConnectionEndpointConfigurationResultDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    11, /* .membersSize */
    ConnectionEndpointConfigurationResultDataType_members  /* .members */
},
/* ConnectionEndpointParameterDataType */
{
    UA_TYPENAME("ConnectionEndpointParameterDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3009LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5039LU}}, /* .binaryEncodingId */
    sizeof(UA_ConnectionEndpointParameterDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    8, /* .membersSize */
    ConnectionEndpointParameterDataType_members  /* .members */
},
/* PubSubConnectionEndpointParameterDataType */
{
    UA_TYPENAME("PubSubConnectionEndpointParameterDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3006LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5060LU}}, /* .binaryEncodingId */
    sizeof(UA_PubSubConnectionEndpointParameterDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    9, /* .membersSize */
    PubSubConnectionEndpointParameterDataType_members  /* .members */
},
};

