/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#include "types_uafx_ac_generated.h"

/* FxVersion */
static UA_DataTypeMember FxVersion_members[4] = {
{
    UA_TYPENAME("Major") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Minor") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_FxVersion, minor) - offsetof(UA_FxVersion, major) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Build") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_FxVersion, build) - offsetof(UA_FxVersion, minor) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("SubBuild") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_FxVersion, subBuild) - offsetof(UA_FxVersion, build) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PublisherQosDataType */
static UA_DataTypeMember PublisherQosDataType_members[2] = {
{
    UA_TYPENAME("QosCategory") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("DatagramQos") /* .memberName */
    &UA_TYPES[UA_TYPES_EXTENSIONOBJECT], /* .memberType */
    offsetof(UA_PublisherQosDataType, datagramQosSize) - offsetof(UA_PublisherQosDataType, qosCategory) - sizeof(UA_String), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};

/* SubscriberQosDataType */
static UA_DataTypeMember SubscriberQosDataType_members[2] = {
{
    UA_TYPENAME("QosCategory") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("DatagramQos") /* .memberName */
    &UA_TYPES[UA_TYPES_EXTENSIONOBJECT], /* .memberType */
    offsetof(UA_SubscriberQosDataType, datagramQosSize) - offsetof(UA_SubscriberQosDataType, qosCategory) - sizeof(UA_String), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};

/* ApplicationId */
static UA_DataTypeMember ApplicationId_members[4] = {
{
    UA_TYPENAME("IdNumeric") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT32], /* .memberType */
    offsetof(UA_ApplicationId, fields.idNumeric), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("IdString") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    offsetof(UA_ApplicationId, fields.idString), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("IdGuid") /* .memberName */
    &UA_TYPES[UA_TYPES_GUID], /* .memberType */
    offsetof(UA_ApplicationId, fields.idGuid), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("IdByteString") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTESTRING], /* .memberType */
    offsetof(UA_ApplicationId, fields.idByteString), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* ClampKindEnum */
#define ClampKindEnum_members NULL

/* ConnectionEndpointStatusEnum */
#define ConnectionEndpointStatusEnum_members NULL

/* FxTimeUnitsEnum */
#define FxTimeUnitsEnum_members NULL

/* SocketKindEnum */
#define SocketKindEnum_members NULL

/* CommHealthOptionSet */
#define CommHealthOptionSet_members NULL

/* DeviceHealthOptionSet */
#define DeviceHealthOptionSet_members NULL

/* OperationalHealthOptionSet */
#define OperationalHealthOptionSet_members NULL

/* AggregatedHealthDataType */
static UA_DataTypeMember AggregatedHealthDataType_members[2] = {
{
    UA_TYPENAME("AggregatedDeviceHealth") /* .memberName */
    &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_DEVICEHEALTHOPTIONSET], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("AggregatedOperationalHealth") /* .memberName */
    &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_OPERATIONALHEALTHOPTIONSET], /* .memberType */
    offsetof(UA_AggregatedHealthDataType, aggregatedOperationalHealth) - offsetof(UA_AggregatedHealthDataType, aggregatedDeviceHealth) - sizeof(UA_DeviceHealthOptionSet), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* ApplicationIdentifierDataType */
static UA_DataTypeMember ApplicationIdentifierDataType_members[2] = {
{
    UA_TYPENAME("Name") /* .memberName */
    &UA_TYPES[UA_TYPES_LOCALIZEDTEXT], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("UniqueIdentifier") /* .memberName */
    &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONID], /* .memberType */
    offsetof(UA_ApplicationIdentifierDataType, uniqueIdentifier) - offsetof(UA_ApplicationIdentifierDataType, name) - sizeof(UA_LocalizedText), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* IntervalRange */
static UA_DataTypeMember IntervalRange_members[5] = {
{
    UA_TYPENAME("Min") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT32], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Max") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT32], /* .memberType */
    offsetof(UA_IntervalRange, max) - offsetof(UA_IntervalRange, min) - sizeof(UA_UInt32), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Increment") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_IntervalRange, increment) - offsetof(UA_IntervalRange, max) - sizeof(UA_UInt32), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Multiplier") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_IntervalRange, multiplier) - offsetof(UA_IntervalRange, increment) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Unit") /* .memberName */
    &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXTIMEUNITSENUM], /* .memberType */
    offsetof(UA_IntervalRange, unit) - offsetof(UA_IntervalRange, multiplier) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};
UA_DataType UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_COUNT] = {
/* FxVersion */
{
    UA_TYPENAME("FxVersion") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {25LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {91LU}}, /* .binaryEncodingId */
    sizeof(UA_FxVersion), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    true, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    FxVersion_members  /* .members */
},
/* PublisherQosDataType */
{
    UA_TYPENAME("PublisherQosDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3011LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5024LU}}, /* .binaryEncodingId */
    sizeof(UA_PublisherQosDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    PublisherQosDataType_members  /* .members */
},
/* SubscriberQosDataType */
{
    UA_TYPENAME("SubscriberQosDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3012LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5027LU}}, /* .binaryEncodingId */
    sizeof(UA_SubscriberQosDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    SubscriberQosDataType_members  /* .members */
},
/* ApplicationId */
{
    UA_TYPENAME("ApplicationId") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3013LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5003LU}}, /* .binaryEncodingId */
    sizeof(UA_ApplicationId), /* .memSize */
    UA_DATATYPEKIND_UNION, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    ApplicationId_members  /* .members */
},
/* ClampKindEnum */
{
    UA_TYPENAME("ClampKindEnum") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3001LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_ClampKindEnum), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    ClampKindEnum_members  /* .members */
},
/* ConnectionEndpointStatusEnum */
{
    UA_TYPENAME("ConnectionEndpointStatusEnum") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3007LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_ConnectionEndpointStatusEnum), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    ConnectionEndpointStatusEnum_members  /* .members */
},
/* FxTimeUnitsEnum */
{
    UA_TYPENAME("FxTimeUnitsEnum") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3006LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_FxTimeUnitsEnum), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    FxTimeUnitsEnum_members  /* .members */
},
/* SocketKindEnum */
{
    UA_TYPENAME("SocketKindEnum") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3002LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_SocketKindEnum), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    SocketKindEnum_members  /* .members */
},
/* CommHealthOptionSet */
{
    UA_TYPENAME("CommHealthOptionSet") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3004LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_CommHealthOptionSet), /* .memSize */
    UA_DATATYPEKIND_UINT16, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    CommHealthOptionSet_members  /* .members */
},
/* DeviceHealthOptionSet */
{
    UA_TYPENAME("DeviceHealthOptionSet") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3005LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_DeviceHealthOptionSet), /* .memSize */
    UA_DATATYPEKIND_UINT16, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    DeviceHealthOptionSet_members  /* .members */
},
/* OperationalHealthOptionSet */
{
    UA_TYPENAME("OperationalHealthOptionSet") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3010LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_OperationalHealthOptionSet), /* .memSize */
    UA_DATATYPEKIND_UINT32, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    OperationalHealthOptionSet_members  /* .members */
},
/* AggregatedHealthDataType */
{
    UA_TYPENAME("AggregatedHealthDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3003LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5004LU}}, /* .binaryEncodingId */
    sizeof(UA_AggregatedHealthDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    true, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    AggregatedHealthDataType_members  /* .members */
},
/* ApplicationIdentifierDataType */
{
    UA_TYPENAME("ApplicationIdentifierDataType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {28LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {60LU}}, /* .binaryEncodingId */
    sizeof(UA_ApplicationIdentifierDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    ApplicationIdentifierDataType_members  /* .members */
},
/* IntervalRange */
{
    UA_TYPENAME("IntervalRange") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3008LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5019LU}}, /* .binaryEncodingId */
    sizeof(UA_IntervalRange), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    true, /* .pointerFree */
    false, /* .overlayable */
    5, /* .membersSize */
    IntervalRange_members  /* .members */
},
};

