/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#ifndef TYPES_UAFX_AC_GENERATED_HANDLING_H_
#define TYPES_UAFX_AC_GENERATED_HANDLING_H_

#include "types_uafx_ac_generated.h"

_UA_BEGIN_DECLS

#if defined(__GNUC__) && __GNUC__ >= 4 && __GNUC_MINOR__ >= 6
# pragma GCC diagnostic push
# pragma GCC diagnostic ignored "-Wmissing-field-initializers"
# pragma GCC diagnostic ignored "-Wmissing-braces"
#endif


/* FxVersion */
static UA_INLINE void
UA_FxVersion_init(UA_FxVersion *p) {
    memset(p, 0, sizeof(UA_FxVersion));
}

static UA_INLINE UA_FxVersion *
UA_FxVersion_new(void) {
    return (UA_FxVersion*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXVERSION]);
}

static UA_INLINE UA_StatusCode
UA_FxVersion_copy(const UA_FxVersion *src, UA_FxVersion *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXVERSION]);
}

UA_DEPRECATED static UA_INLINE void
UA_FxVersion_deleteMembers(UA_FxVersion *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXVERSION]);
}

static UA_INLINE void
UA_FxVersion_clear(UA_FxVersion *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXVERSION]);
}

static UA_INLINE void
UA_FxVersion_delete(UA_FxVersion *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXVERSION]);
}static UA_INLINE UA_Boolean
UA_FxVersion_equal(const UA_FxVersion *p1, const UA_FxVersion *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXVERSION]) == UA_ORDER_EQ);
}



/* PublisherQosDataType */
static UA_INLINE void
UA_PublisherQosDataType_init(UA_PublisherQosDataType *p) {
    memset(p, 0, sizeof(UA_PublisherQosDataType));
}

static UA_INLINE UA_PublisherQosDataType *
UA_PublisherQosDataType_new(void) {
    return (UA_PublisherQosDataType*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_PUBLISHERQOSDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_PublisherQosDataType_copy(const UA_PublisherQosDataType *src, UA_PublisherQosDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_PUBLISHERQOSDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_PublisherQosDataType_deleteMembers(UA_PublisherQosDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_PUBLISHERQOSDATATYPE]);
}

static UA_INLINE void
UA_PublisherQosDataType_clear(UA_PublisherQosDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_PUBLISHERQOSDATATYPE]);
}

static UA_INLINE void
UA_PublisherQosDataType_delete(UA_PublisherQosDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_PUBLISHERQOSDATATYPE]);
}static UA_INLINE UA_Boolean
UA_PublisherQosDataType_equal(const UA_PublisherQosDataType *p1, const UA_PublisherQosDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_PUBLISHERQOSDATATYPE]) == UA_ORDER_EQ);
}



/* SubscriberQosDataType */
static UA_INLINE void
UA_SubscriberQosDataType_init(UA_SubscriberQosDataType *p) {
    memset(p, 0, sizeof(UA_SubscriberQosDataType));
}

static UA_INLINE UA_SubscriberQosDataType *
UA_SubscriberQosDataType_new(void) {
    return (UA_SubscriberQosDataType*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SUBSCRIBERQOSDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_SubscriberQosDataType_copy(const UA_SubscriberQosDataType *src, UA_SubscriberQosDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SUBSCRIBERQOSDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_SubscriberQosDataType_deleteMembers(UA_SubscriberQosDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SUBSCRIBERQOSDATATYPE]);
}

static UA_INLINE void
UA_SubscriberQosDataType_clear(UA_SubscriberQosDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SUBSCRIBERQOSDATATYPE]);
}

static UA_INLINE void
UA_SubscriberQosDataType_delete(UA_SubscriberQosDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SUBSCRIBERQOSDATATYPE]);
}static UA_INLINE UA_Boolean
UA_SubscriberQosDataType_equal(const UA_SubscriberQosDataType *p1, const UA_SubscriberQosDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SUBSCRIBERQOSDATATYPE]) == UA_ORDER_EQ);
}



/* ApplicationId */
static UA_INLINE void
UA_ApplicationId_init(UA_ApplicationId *p) {
    memset(p, 0, sizeof(UA_ApplicationId));
}

static UA_INLINE UA_ApplicationId *
UA_ApplicationId_new(void) {
    return (UA_ApplicationId*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONID]);
}

static UA_INLINE UA_StatusCode
UA_ApplicationId_copy(const UA_ApplicationId *src, UA_ApplicationId *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONID]);
}

UA_DEPRECATED static UA_INLINE void
UA_ApplicationId_deleteMembers(UA_ApplicationId *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONID]);
}

static UA_INLINE void
UA_ApplicationId_clear(UA_ApplicationId *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONID]);
}

static UA_INLINE void
UA_ApplicationId_delete(UA_ApplicationId *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONID]);
}static UA_INLINE UA_Boolean
UA_ApplicationId_equal(const UA_ApplicationId *p1, const UA_ApplicationId *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONID]) == UA_ORDER_EQ);
}



/* ClampKindEnum */
static UA_INLINE void
UA_ClampKindEnum_init(UA_ClampKindEnum *p) {
    memset(p, 0, sizeof(UA_ClampKindEnum));
}

static UA_INLINE UA_ClampKindEnum *
UA_ClampKindEnum_new(void) {
    return (UA_ClampKindEnum*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CLAMPKINDENUM]);
}

static UA_INLINE UA_StatusCode
UA_ClampKindEnum_copy(const UA_ClampKindEnum *src, UA_ClampKindEnum *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CLAMPKINDENUM]);
}

UA_DEPRECATED static UA_INLINE void
UA_ClampKindEnum_deleteMembers(UA_ClampKindEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CLAMPKINDENUM]);
}

static UA_INLINE void
UA_ClampKindEnum_clear(UA_ClampKindEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CLAMPKINDENUM]);
}

static UA_INLINE void
UA_ClampKindEnum_delete(UA_ClampKindEnum *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CLAMPKINDENUM]);
}static UA_INLINE UA_Boolean
UA_ClampKindEnum_equal(const UA_ClampKindEnum *p1, const UA_ClampKindEnum *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CLAMPKINDENUM]) == UA_ORDER_EQ);
}



/* ConnectionEndpointStatusEnum */
static UA_INLINE void
UA_ConnectionEndpointStatusEnum_init(UA_ConnectionEndpointStatusEnum *p) {
    memset(p, 0, sizeof(UA_ConnectionEndpointStatusEnum));
}

static UA_INLINE UA_ConnectionEndpointStatusEnum *
UA_ConnectionEndpointStatusEnum_new(void) {
    return (UA_ConnectionEndpointStatusEnum*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CONNECTIONENDPOINTSTATUSENUM]);
}

static UA_INLINE UA_StatusCode
UA_ConnectionEndpointStatusEnum_copy(const UA_ConnectionEndpointStatusEnum *src, UA_ConnectionEndpointStatusEnum *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CONNECTIONENDPOINTSTATUSENUM]);
}

UA_DEPRECATED static UA_INLINE void
UA_ConnectionEndpointStatusEnum_deleteMembers(UA_ConnectionEndpointStatusEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CONNECTIONENDPOINTSTATUSENUM]);
}

static UA_INLINE void
UA_ConnectionEndpointStatusEnum_clear(UA_ConnectionEndpointStatusEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CONNECTIONENDPOINTSTATUSENUM]);
}

static UA_INLINE void
UA_ConnectionEndpointStatusEnum_delete(UA_ConnectionEndpointStatusEnum *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CONNECTIONENDPOINTSTATUSENUM]);
}static UA_INLINE UA_Boolean
UA_ConnectionEndpointStatusEnum_equal(const UA_ConnectionEndpointStatusEnum *p1, const UA_ConnectionEndpointStatusEnum *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_CONNECTIONENDPOINTSTATUSENUM]) == UA_ORDER_EQ);
}



/* FxTimeUnitsEnum */
static UA_INLINE void
UA_FxTimeUnitsEnum_init(UA_FxTimeUnitsEnum *p) {
    memset(p, 0, sizeof(UA_FxTimeUnitsEnum));
}

static UA_INLINE UA_FxTimeUnitsEnum *
UA_FxTimeUnitsEnum_new(void) {
    return (UA_FxTimeUnitsEnum*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXTIMEUNITSENUM]);
}

static UA_INLINE UA_StatusCode
UA_FxTimeUnitsEnum_copy(const UA_FxTimeUnitsEnum *src, UA_FxTimeUnitsEnum *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXTIMEUNITSENUM]);
}

UA_DEPRECATED static UA_INLINE void
UA_FxTimeUnitsEnum_deleteMembers(UA_FxTimeUnitsEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXTIMEUNITSENUM]);
}

static UA_INLINE void
UA_FxTimeUnitsEnum_clear(UA_FxTimeUnitsEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXTIMEUNITSENUM]);
}

static UA_INLINE void
UA_FxTimeUnitsEnum_delete(UA_FxTimeUnitsEnum *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXTIMEUNITSENUM]);
}static UA_INLINE UA_Boolean
UA_FxTimeUnitsEnum_equal(const UA_FxTimeUnitsEnum *p1, const UA_FxTimeUnitsEnum *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_FXTIMEUNITSENUM]) == UA_ORDER_EQ);
}



/* SocketKindEnum */
static UA_INLINE void
UA_SocketKindEnum_init(UA_SocketKindEnum *p) {
    memset(p, 0, sizeof(UA_SocketKindEnum));
}

static UA_INLINE UA_SocketKindEnum *
UA_SocketKindEnum_new(void) {
    return (UA_SocketKindEnum*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SOCKETKINDENUM]);
}

static UA_INLINE UA_StatusCode
UA_SocketKindEnum_copy(const UA_SocketKindEnum *src, UA_SocketKindEnum *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SOCKETKINDENUM]);
}

UA_DEPRECATED static UA_INLINE void
UA_SocketKindEnum_deleteMembers(UA_SocketKindEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SOCKETKINDENUM]);
}

static UA_INLINE void
UA_SocketKindEnum_clear(UA_SocketKindEnum *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SOCKETKINDENUM]);
}

static UA_INLINE void
UA_SocketKindEnum_delete(UA_SocketKindEnum *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SOCKETKINDENUM]);
}static UA_INLINE UA_Boolean
UA_SocketKindEnum_equal(const UA_SocketKindEnum *p1, const UA_SocketKindEnum *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_SOCKETKINDENUM]) == UA_ORDER_EQ);
}



/* CommHealthOptionSet */
static UA_INLINE void
UA_CommHealthOptionSet_init(UA_CommHealthOptionSet *p) {
    memset(p, 0, sizeof(UA_CommHealthOptionSet));
}

static UA_INLINE UA_CommHealthOptionSet *
UA_CommHealthOptionSet_new(void) {
    return (UA_CommHealthOptionSet*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_COMMHEALTHOPTIONSET]);
}

static UA_INLINE UA_StatusCode
UA_CommHealthOptionSet_copy(const UA_CommHealthOptionSet *src, UA_CommHealthOptionSet *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_COMMHEALTHOPTIONSET]);
}

UA_DEPRECATED static UA_INLINE void
UA_CommHealthOptionSet_deleteMembers(UA_CommHealthOptionSet *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_COMMHEALTHOPTIONSET]);
}

static UA_INLINE void
UA_CommHealthOptionSet_clear(UA_CommHealthOptionSet *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_COMMHEALTHOPTIONSET]);
}

static UA_INLINE void
UA_CommHealthOptionSet_delete(UA_CommHealthOptionSet *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_COMMHEALTHOPTIONSET]);
}static UA_INLINE UA_Boolean
UA_CommHealthOptionSet_equal(const UA_CommHealthOptionSet *p1, const UA_CommHealthOptionSet *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_COMMHEALTHOPTIONSET]) == UA_ORDER_EQ);
}



/* DeviceHealthOptionSet */
static UA_INLINE void
UA_DeviceHealthOptionSet_init(UA_DeviceHealthOptionSet *p) {
    memset(p, 0, sizeof(UA_DeviceHealthOptionSet));
}

static UA_INLINE UA_DeviceHealthOptionSet *
UA_DeviceHealthOptionSet_new(void) {
    return (UA_DeviceHealthOptionSet*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_DEVICEHEALTHOPTIONSET]);
}

static UA_INLINE UA_StatusCode
UA_DeviceHealthOptionSet_copy(const UA_DeviceHealthOptionSet *src, UA_DeviceHealthOptionSet *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_DEVICEHEALTHOPTIONSET]);
}

UA_DEPRECATED static UA_INLINE void
UA_DeviceHealthOptionSet_deleteMembers(UA_DeviceHealthOptionSet *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_DEVICEHEALTHOPTIONSET]);
}

static UA_INLINE void
UA_DeviceHealthOptionSet_clear(UA_DeviceHealthOptionSet *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_DEVICEHEALTHOPTIONSET]);
}

static UA_INLINE void
UA_DeviceHealthOptionSet_delete(UA_DeviceHealthOptionSet *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_DEVICEHEALTHOPTIONSET]);
}static UA_INLINE UA_Boolean
UA_DeviceHealthOptionSet_equal(const UA_DeviceHealthOptionSet *p1, const UA_DeviceHealthOptionSet *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_DEVICEHEALTHOPTIONSET]) == UA_ORDER_EQ);
}



/* OperationalHealthOptionSet */
static UA_INLINE void
UA_OperationalHealthOptionSet_init(UA_OperationalHealthOptionSet *p) {
    memset(p, 0, sizeof(UA_OperationalHealthOptionSet));
}

static UA_INLINE UA_OperationalHealthOptionSet *
UA_OperationalHealthOptionSet_new(void) {
    return (UA_OperationalHealthOptionSet*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_OPERATIONALHEALTHOPTIONSET]);
}

static UA_INLINE UA_StatusCode
UA_OperationalHealthOptionSet_copy(const UA_OperationalHealthOptionSet *src, UA_OperationalHealthOptionSet *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_OPERATIONALHEALTHOPTIONSET]);
}

UA_DEPRECATED static UA_INLINE void
UA_OperationalHealthOptionSet_deleteMembers(UA_OperationalHealthOptionSet *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_OPERATIONALHEALTHOPTIONSET]);
}

static UA_INLINE void
UA_OperationalHealthOptionSet_clear(UA_OperationalHealthOptionSet *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_OPERATIONALHEALTHOPTIONSET]);
}

static UA_INLINE void
UA_OperationalHealthOptionSet_delete(UA_OperationalHealthOptionSet *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_OPERATIONALHEALTHOPTIONSET]);
}static UA_INLINE UA_Boolean
UA_OperationalHealthOptionSet_equal(const UA_OperationalHealthOptionSet *p1, const UA_OperationalHealthOptionSet *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_OPERATIONALHEALTHOPTIONSET]) == UA_ORDER_EQ);
}



/* AggregatedHealthDataType */
static UA_INLINE void
UA_AggregatedHealthDataType_init(UA_AggregatedHealthDataType *p) {
    memset(p, 0, sizeof(UA_AggregatedHealthDataType));
}

static UA_INLINE UA_AggregatedHealthDataType *
UA_AggregatedHealthDataType_new(void) {
    return (UA_AggregatedHealthDataType*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_AGGREGATEDHEALTHDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_AggregatedHealthDataType_copy(const UA_AggregatedHealthDataType *src, UA_AggregatedHealthDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_AGGREGATEDHEALTHDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_AggregatedHealthDataType_deleteMembers(UA_AggregatedHealthDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_AGGREGATEDHEALTHDATATYPE]);
}

static UA_INLINE void
UA_AggregatedHealthDataType_clear(UA_AggregatedHealthDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_AGGREGATEDHEALTHDATATYPE]);
}

static UA_INLINE void
UA_AggregatedHealthDataType_delete(UA_AggregatedHealthDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_AGGREGATEDHEALTHDATATYPE]);
}static UA_INLINE UA_Boolean
UA_AggregatedHealthDataType_equal(const UA_AggregatedHealthDataType *p1, const UA_AggregatedHealthDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_AGGREGATEDHEALTHDATATYPE]) == UA_ORDER_EQ);
}



/* ApplicationIdentifierDataType */
static UA_INLINE void
UA_ApplicationIdentifierDataType_init(UA_ApplicationIdentifierDataType *p) {
    memset(p, 0, sizeof(UA_ApplicationIdentifierDataType));
}

static UA_INLINE UA_ApplicationIdentifierDataType *
UA_ApplicationIdentifierDataType_new(void) {
    return (UA_ApplicationIdentifierDataType*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONIDENTIFIERDATATYPE]);
}

static UA_INLINE UA_StatusCode
UA_ApplicationIdentifierDataType_copy(const UA_ApplicationIdentifierDataType *src, UA_ApplicationIdentifierDataType *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONIDENTIFIERDATATYPE]);
}

UA_DEPRECATED static UA_INLINE void
UA_ApplicationIdentifierDataType_deleteMembers(UA_ApplicationIdentifierDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONIDENTIFIERDATATYPE]);
}

static UA_INLINE void
UA_ApplicationIdentifierDataType_clear(UA_ApplicationIdentifierDataType *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONIDENTIFIERDATATYPE]);
}

static UA_INLINE void
UA_ApplicationIdentifierDataType_delete(UA_ApplicationIdentifierDataType *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONIDENTIFIERDATATYPE]);
}static UA_INLINE UA_Boolean
UA_ApplicationIdentifierDataType_equal(const UA_ApplicationIdentifierDataType *p1, const UA_ApplicationIdentifierDataType *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_APPLICATIONIDENTIFIERDATATYPE]) == UA_ORDER_EQ);
}



/* IntervalRange */
static UA_INLINE void
UA_IntervalRange_init(UA_IntervalRange *p) {
    memset(p, 0, sizeof(UA_IntervalRange));
}

static UA_INLINE UA_IntervalRange *
UA_IntervalRange_new(void) {
    return (UA_IntervalRange*)UA_new(&UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_INTERVALRANGE]);
}

static UA_INLINE UA_StatusCode
UA_IntervalRange_copy(const UA_IntervalRange *src, UA_IntervalRange *dst) {
    return UA_copy(src, dst, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_INTERVALRANGE]);
}

UA_DEPRECATED static UA_INLINE void
UA_IntervalRange_deleteMembers(UA_IntervalRange *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_INTERVALRANGE]);
}

static UA_INLINE void
UA_IntervalRange_clear(UA_IntervalRange *p) {
    UA_clear(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_INTERVALRANGE]);
}

static UA_INLINE void
UA_IntervalRange_delete(UA_IntervalRange *p) {
    UA_delete(p, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_INTERVALRANGE]);
}static UA_INLINE UA_Boolean
UA_IntervalRange_equal(const UA_IntervalRange *p1, const UA_IntervalRange *p2) {
    return (UA_order(p1, p2, &UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_INTERVALRANGE]) == UA_ORDER_EQ);
}



#if defined(__GNUC__) && __GNUC__ >= 4 && __GNUC_MINOR__ >= 6
# pragma GCC diagnostic pop
#endif

_UA_END_DECLS

#endif /* TYPES_UAFX_AC_GENERATED_HANDLING_H_ */
