/**********************************
 * Autogenerated -- do not modify *
 **********************************/

/* Must be before the include guards */
#ifdef UA_ENABLE_AMALGAMATION
# include "open62541.h"
#else
# include <open62541/types.h>
#endif

#ifndef TYPES_UAFX_DATA_GENERATED_H_
#define TYPES_UAFX_DATA_GENERATED_H_

#include "types_di_generated.h"

_UA_BEGIN_DECLS

/**
 * Every type is assigned an index in an array containing the type descriptions.
 * These descriptions are used during type handling (copying, deletion,
 * binary encoding, ...). */
#define UA_TYPES_UAFX_DATA_COUNT 22
extern UA_EXPORT UA_DataType UA_TYPES_UAFX_DATA[UA_TYPES_UAFX_DATA_COUNT];

/* PubSubCommunicationConfigurationDataType */
typedef struct {
    UA_PubSubConfiguration2DataType pubSubConfiguration;
    UA_Boolean requireCompleteUpdate;
    size_t configurationReferencesSize;
    UA_PubSubConfigurationRefDataType *configurationReferences;
} UA_PubSubCommunicationConfigurationDataType;

#define UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONDATATYPE 0

/* PubSubCommunicationConfigurationResultDataType */
typedef struct {
    UA_StatusCode result;
    UA_Boolean changesApplied;
    size_t referenceResultsSize;
    UA_StatusCode *referenceResults;
    size_t configurationValuesSize;
    UA_PubSubConfigurationValueDataType *configurationValues;
    size_t configurationObjectsSize;
    UA_NodeId *configurationObjects;
} UA_PubSubCommunicationConfigurationResultDataType;

#define UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONCONFIGURATIONRESULTDATATYPE 1

/* PubSubCommunicationLinkConfigurationDataType */
typedef struct {
    UA_PubSubConfigurationRefDataType dataSetReaderRef;
    UA_ConfigurationVersionDataType expectedSubscribedDataSetVersion;
    UA_PubSubConfigurationRefDataType dataSetWriterRef;
    UA_ConfigurationVersionDataType expectedPublishedDataSetVersion;
} UA_PubSubCommunicationLinkConfigurationDataType;

#define UA_TYPES_UAFX_DATA_PUBSUBCOMMUNICATIONLINKCONFIGURATIONDATATYPE 2

/* NodeIdArray */
typedef struct {
    UA_NodeId node;
    size_t arrayIndexSize;
    UA_UInt32 *arrayIndex;
} UA_NodeIdArray;

#define UA_TYPES_UAFX_DATA_NODEIDARRAY 3

/* NodeIdValuePair */
typedef struct {
    UA_NodeIdArray key;
    UA_Variant value;
} UA_NodeIdValuePair;

#define UA_TYPES_UAFX_DATA_NODEIDVALUEPAIR 4

/* RelatedEndpointDataType */
typedef struct {
    UA_String address;
    size_t connectionEndpointPathSize;
    UA_PortableQualifiedName *connectionEndpointPath;
    UA_String connectionEndpointName;
} UA_RelatedEndpointDataType;

#define UA_TYPES_UAFX_DATA_RELATEDENDPOINTDATATYPE 5

/* PubSubReserveCommunicationIdsDataType */
typedef struct {
    UA_String transportProfileUri;
    UA_UInt16 numReqWriterGroupIds;
    UA_UInt16 numReqDataSetWriterIds;
} UA_PubSubReserveCommunicationIdsDataType;

#define UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSDATATYPE 6

/* PubSubReserveCommunicationIds2DataType */
typedef struct {
    UA_String transportProfileUri;
    UA_UInt16 numReqWriterGroupIds;
    UA_UInt16 numReqDataSetWriterIds;
    UA_Boolean requestTransportSpecificInfo;
} UA_PubSubReserveCommunicationIds2DataType;

#define UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDS2DATATYPE 7

/* PubSubReserveCommunicationIdsResultDataType */
typedef struct {
    UA_StatusCode result;
    UA_Variant defaultPublisherId;
    size_t writerGroupIdsSize;
    UA_UInt16 *writerGroupIds;
    size_t dataSetWriterIdsSize;
    UA_UInt16 *dataSetWriterIds;
} UA_PubSubReserveCommunicationIdsResultDataType;

#define UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULTDATATYPE 8

/* PubSubReserveCommunicationIdsResult2DataType */
typedef struct {
    UA_StatusCode result;
    UA_Variant defaultPublisherId;
    size_t writerGroupIdsSize;
    UA_UInt16 *writerGroupIds;
    size_t dataSetWriterIdsSize;
    UA_UInt16 *dataSetWriterIds;
    UA_Variant transportSpecificInfo;
} UA_PubSubReserveCommunicationIdsResult2DataType;

#define UA_TYPES_UAFX_DATA_PUBSUBRESERVECOMMUNICATIONIDSRESULT2DATATYPE 9

/* ConnectionEndpointDefinitionDataType */
typedef enum {
    UA_CONNECTIONENDPOINTDEFINITIONDATATYPESWITCH_NONE = 0,
    UA_CONNECTIONENDPOINTDEFINITIONDATATYPESWITCH_PARAMETER = 1,
    UA_CONNECTIONENDPOINTDEFINITIONDATATYPESWITCH_NODE = 2,
    __UA_CONNECTIONENDPOINTDEFINITIONDATATYPESWITCH_FORCE32BIT = 0x7fffffff
} UA_ConnectionEndpointDefinitionDataTypeSwitch;

UA_STATIC_ASSERT(sizeof(UA_ConnectionEndpointDefinitionDataTypeSwitch) == sizeof(UA_Int32), enum_must_be_32bit);

typedef struct {
    UA_ConnectionEndpointDefinitionDataTypeSwitch switchField;
    union {
        UA_ExtensionObject parameter;
        UA_NodeId node;
    } fields;
} UA_ConnectionEndpointDefinitionDataType;

#define UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTDEFINITIONDATATYPE 10

/* AssetVerificationModeEnum */
typedef enum {
    UA_ASSETVERIFICATIONMODEENUM_ASSETCOMPATIBILITY = 0,
    UA_ASSETVERIFICATIONMODEENUM_ASSETIDENTITY = 1,
    UA_ASSETVERIFICATIONMODEENUM_ASSETIDENTITYANDCOMPATIBILITY = 2,
    __UA_ASSETVERIFICATIONMODEENUM_FORCE32BIT = 0x7fffffff
} UA_AssetVerificationModeEnum;

UA_STATIC_ASSERT(sizeof(UA_AssetVerificationModeEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_UAFX_DATA_ASSETVERIFICATIONMODEENUM 11

/* AssetVerificationResultEnum */
typedef enum {
    UA_ASSETVERIFICATIONRESULTENUM_NOTSET = 0,
    UA_ASSETVERIFICATIONRESULTENUM_MATCH = 1,
    UA_ASSETVERIFICATIONRESULTENUM_COMPATIBLE = 2,
    UA_ASSETVERIFICATIONRESULTENUM_MISMATCH = 3,
    __UA_ASSETVERIFICATIONRESULTENUM_FORCE32BIT = 0x7fffffff
} UA_AssetVerificationResultEnum;

UA_STATIC_ASSERT(sizeof(UA_AssetVerificationResultEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTENUM 12

/* FunctionalEntityVerificationResultEnum */
typedef enum {
    UA_FUNCTIONALENTITYVERIFICATIONRESULTENUM_NOTSET = 0,
    UA_FUNCTIONALENTITYVERIFICATIONRESULTENUM_MATCH = 1,
    UA_FUNCTIONALENTITYVERIFICATIONRESULTENUM_MISMATCH = 2,
    __UA_FUNCTIONALENTITYVERIFICATIONRESULTENUM_FORCE32BIT = 0x7fffffff
} UA_FunctionalEntityVerificationResultEnum;

UA_STATIC_ASSERT(sizeof(UA_FunctionalEntityVerificationResultEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_UAFX_DATA_FUNCTIONALENTITYVERIFICATIONRESULTENUM 13

/* PubSubConnectionEndpointModeEnum */
typedef enum {
    UA_PUBSUBCONNECTIONENDPOINTMODEENUM_PUBLISHERSUBSCRIBER = 1,
    UA_PUBSUBCONNECTIONENDPOINTMODEENUM_PUBLISHER = 2,
    UA_PUBSUBCONNECTIONENDPOINTMODEENUM_SUBSCRIBER = 3,
    __UA_PUBSUBCONNECTIONENDPOINTMODEENUM_FORCE32BIT = 0x7fffffff
} UA_PubSubConnectionEndpointModeEnum;

UA_STATIC_ASSERT(sizeof(UA_PubSubConnectionEndpointModeEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTMODEENUM 14

/* FxCommandMask: This OptionSet defines flags indicating the commands a ConnectionManager may use in its call to the EstablishConnections Method. */
typedef UA_UInt32 UA_FxCommandMask;

#define UA_FXCOMMANDMASK_VERIFYASSETCMD 0
#define UA_FXCOMMANDMASK_VERIFYFUNCTIONALENTITYCMD 1
#define UA_FXCOMMANDMASK_CREATECONNECTIONENDPOINTCMD 2
#define UA_FXCOMMANDMASK_ESTABLISHCONTROLCMD 3
#define UA_FXCOMMANDMASK_SETCONFIGURATIONDATACMD 4
#define UA_FXCOMMANDMASK_REASSIGNCONTROLCMD 5
#define UA_FXCOMMANDMASK_RESERVECOMMUNICATIONIDSCMD 6
#define UA_FXCOMMANDMASK_SETCOMMUNICATIONCONFIGURATIONCMD 7
#define UA_FXCOMMANDMASK_ENABLECOMMUNICATIONCMD 8

#define UA_TYPES_UAFX_DATA_FXCOMMANDMASK 15

/* AssetVerificationDataType */
typedef struct {
    UA_NodeId assetToVerify;
    UA_AssetVerificationModeEnum verificationMode;
    UA_AssetVerificationResultEnum expectedVerificationResult;
    size_t expectedVerificationVariablesSize;
    UA_KeyValuePair *expectedVerificationVariables;
    size_t expectedAdditionalVerificationVariablesSize;
    UA_NodeIdValuePair *expectedAdditionalVerificationVariables;
} UA_AssetVerificationDataType;

#define UA_TYPES_UAFX_DATA_ASSETVERIFICATIONDATATYPE 16

/* AssetVerificationResultDataType */
typedef struct {
    UA_StatusCode verificationStatus;
    UA_AssetVerificationResultEnum verificationResult;
    size_t verificationVariablesErrorsSize;
    UA_StatusCode *verificationVariablesErrors;
    size_t verificationAdditionalVariablesErrorsSize;
    UA_StatusCode *verificationAdditionalVariablesErrors;
} UA_AssetVerificationResultDataType;

#define UA_TYPES_UAFX_DATA_ASSETVERIFICATIONRESULTDATATYPE 17

/* ConnectionEndpointConfigurationDataType */
typedef struct {
    UA_NodeId functionalEntityNode;
    UA_ConnectionEndpointDefinitionDataType connectionEndpoint;
    size_t expectedVerificationVariablesSize;
    UA_NodeIdValuePair *expectedVerificationVariables;
    size_t controlGroupsSize;
    UA_NodeId *controlGroups;
    size_t configurationDataSize;
    UA_NodeIdValuePair *configurationData;
    UA_ExtensionObject communicationLinks;
} UA_ConnectionEndpointConfigurationDataType;

#define UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONDATATYPE 18

/* ConnectionEndpointConfigurationResultDataType */
typedef struct {
    UA_NodeId connectionEndpointId;
    UA_StatusCode functionalEntityNodeResult;
    UA_StatusCode connectionEndpointResult;
    UA_FunctionalEntityVerificationResultEnum verificationResult;
    UA_StatusCode verificationStatus;
    size_t verificationVariablesErrorsSize;
    UA_StatusCode *verificationVariablesErrors;
    size_t establishControlResultSize;
    UA_StatusCode *establishControlResult;
    size_t configurationDataResultSize;
    UA_StatusCode *configurationDataResult;
    size_t reassignControlResultSize;
    UA_StatusCode *reassignControlResult;
    UA_StatusCode communicationLinksResult;
    UA_StatusCode enableCommunicationResult;
} UA_ConnectionEndpointConfigurationResultDataType;

#define UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTCONFIGURATIONRESULTDATATYPE 19

/* ConnectionEndpointParameterDataType */
typedef struct {
    UA_String name;
    UA_NodeId connectionEndpointTypeId;
    size_t inputVariableIdsSize;
    UA_NodeId *inputVariableIds;
    size_t outputVariableIdsSize;
    UA_NodeId *outputVariableIds;
    UA_Boolean isPersistent;
    UA_Double cleanupTimeout;
    UA_RelatedEndpointDataType relatedEndpoint;
    UA_Boolean isPreconfigured;
} UA_ConnectionEndpointParameterDataType;

#define UA_TYPES_UAFX_DATA_CONNECTIONENDPOINTPARAMETERDATATYPE 20

/* PubSubConnectionEndpointParameterDataType */
typedef struct {
    UA_String name;
    UA_NodeId connectionEndpointTypeId;
    size_t inputVariableIdsSize;
    UA_NodeId *inputVariableIds;
    size_t outputVariableIdsSize;
    UA_NodeId *outputVariableIds;
    UA_Boolean isPersistent;
    UA_Double cleanupTimeout;
    UA_RelatedEndpointDataType relatedEndpoint;
    UA_Boolean isPreconfigured;
    UA_PubSubConnectionEndpointModeEnum mode;
} UA_PubSubConnectionEndpointParameterDataType;

#define UA_TYPES_UAFX_DATA_PUBSUBCONNECTIONENDPOINTPARAMETERDATATYPE 21


_UA_END_DECLS

#endif /* TYPES_UAFX_DATA_GENERATED_H_ */
