/**********************************
 * Autogenerated -- do not modify *
 **********************************/

/* Must be before the include guards */
#ifdef UA_ENABLE_AMALGAMATION
# include "open62541.h"
#else
# include <open62541/types.h>
#endif

#ifndef TYPES_UAFX_AC_GENERATED_H_
#define TYPES_UAFX_AC_GENERATED_H_

#include "types_uafx_data_generated.h"
#include "types_di_generated.h"

_UA_BEGIN_DECLS

/**
 * Every type is assigned an index in an array containing the type descriptions.
 * These descriptions are used during type handling (copying, deletion,
 * binary encoding, ...). */
#define UA_TYPES_UAFX_AC_COUNT 14
extern UA_EXPORT UA_DataType UA_TYPES_UAFX_AC[UA_TYPES_UAFX_AC_COUNT];

/* FxVersion */
typedef struct {
    UA_UInt16 major;
    UA_UInt16 minor;
    UA_UInt16 build;
    UA_UInt16 subBuild;
} UA_FxVersion;

#define UA_TYPES_UAFX_AC_FXVERSION 0

/* PublisherQosDataType */
typedef struct {
    UA_String qosCategory;
    size_t datagramQosSize;
    UA_ExtensionObject *datagramQos;
} UA_PublisherQosDataType;

#define UA_TYPES_UAFX_AC_PUBLISHERQOSDATATYPE 1

/* SubscriberQosDataType */
typedef struct {
    UA_String qosCategory;
    size_t datagramQosSize;
    UA_ExtensionObject *datagramQos;
} UA_SubscriberQosDataType;

#define UA_TYPES_UAFX_AC_SUBSCRIBERQOSDATATYPE 2

/* ApplicationId */
typedef enum {
    UA_APPLICATIONIDSWITCH_NONE = 0,
    UA_APPLICATIONIDSWITCH_IDNUMERIC = 1,
    UA_APPLICATIONIDSWITCH_IDSTRING = 2,
    UA_APPLICATIONIDSWITCH_IDGUID = 3,
    UA_APPLICATIONIDSWITCH_IDBYTESTRING = 4,
    __UA_APPLICATIONIDSWITCH_FORCE32BIT = 0x7fffffff
} UA_ApplicationIdSwitch;

UA_STATIC_ASSERT(sizeof(UA_ApplicationIdSwitch) == sizeof(UA_Int32), enum_must_be_32bit);

typedef struct {
    UA_ApplicationIdSwitch switchField;
    union {
        UA_UInt32 idNumeric;
        UA_String idString;
        UA_Guid idGuid;
        UA_ByteString idByteString;
    } fields;
} UA_ApplicationId;

#define UA_TYPES_UAFX_AC_APPLICATIONID 3

/* ClampKindEnum */
typedef enum {
    UA_CLAMPKINDENUM_SCREW = 0,
    UA_CLAMPKINDENUM_THUMB = 1,
    __UA_CLAMPKINDENUM_FORCE32BIT = 0x7fffffff
} UA_ClampKindEnum;

UA_STATIC_ASSERT(sizeof(UA_ClampKindEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_UAFX_AC_CLAMPKINDENUM 4

/* ConnectionEndpointStatusEnum: This enumeration defines the values of the FlcConnectionStatus of an FlcConnectionEndpointType.  */
typedef enum {
    UA_CONNECTIONENDPOINTSTATUSENUM_INITIAL = 0,
    UA_CONNECTIONENDPOINTSTATUSENUM_READY = 1,
    UA_CONNECTIONENDPOINTSTATUSENUM_PREOPERATIONAL = 2,
    UA_CONNECTIONENDPOINTSTATUSENUM_OPERATIONAL = 3,
    UA_CONNECTIONENDPOINTSTATUSENUM_ERROR = 4,
    __UA_CONNECTIONENDPOINTSTATUSENUM_FORCE32BIT = 0x7fffffff
} UA_ConnectionEndpointStatusEnum;

UA_STATIC_ASSERT(sizeof(UA_ConnectionEndpointStatusEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_UAFX_AC_CONNECTIONENDPOINTSTATUSENUM 5

/* FxTimeUnitsEnum: This enumeration describes the support units of time */
typedef enum {
    UA_FXTIMEUNITSENUM_NANOSECOND = 0,
    UA_FXTIMEUNITSENUM_MICROSECOND = 1,
    UA_FXTIMEUNITSENUM_MILLISECOND = 2,
    UA_FXTIMEUNITSENUM_SECOND = 3,
    __UA_FXTIMEUNITSENUM_FORCE32BIT = 0x7fffffff
} UA_FxTimeUnitsEnum;

UA_STATIC_ASSERT(sizeof(UA_FxTimeUnitsEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_UAFX_AC_FXTIMEUNITSENUM 6

/* SocketKindEnum */
typedef enum {
    UA_SOCKETKINDENUM_RJ45 = 0,
    UA_SOCKETKINDENUM_M12 = 1,
    __UA_SOCKETKINDENUM_FORCE32BIT = 0x7fffffff
} UA_SocketKindEnum;

UA_STATIC_ASSERT(sizeof(UA_SocketKindEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_UAFX_AC_SOCKETKINDENUM 7

/* CommHealthOptionSet */
typedef UA_UInt16 UA_CommHealthOptionSet;

#define UA_COMMHEALTHOPTIONSET_COMMINITIAL 0
#define UA_COMMHEALTHOPTIONSET_COMMPREOPERATIONAL 1
#define UA_COMMHEALTHOPTIONSET_COMMERROR 2

#define UA_TYPES_UAFX_AC_COMMHEALTHOPTIONSET 8

/* DeviceHealthOptionSet */
typedef UA_UInt16 UA_DeviceHealthOptionSet;

#define UA_DEVICEHEALTHOPTIONSET_DEVICEFAILURE 0
#define UA_DEVICEHEALTHOPTIONSET_DEVICECHECKFUNCTION 1
#define UA_DEVICEHEALTHOPTIONSET_DEVICEMAINTENANCEREQUIRED 2
#define UA_DEVICEHEALTHOPTIONSET_DEVICEOFFSPEC 3

#define UA_TYPES_UAFX_AC_DEVICEHEALTHOPTIONSET 9

/* OperationalHealthOptionSet */
typedef UA_UInt32 UA_OperationalHealthOptionSet;

#define UA_OPERATIONALHEALTHOPTIONSET_OPERATIONALWARNING 16
#define UA_OPERATIONALHEALTHOPTIONSET_OPERATIONALERROR 17
#define UA_OPERATIONALHEALTHOPTIONSET_SUBOPERATIONALWARNING 18
#define UA_OPERATIONALHEALTHOPTIONSET_SUBOPERATIONALERROR 19

#define UA_TYPES_UAFX_AC_OPERATIONALHEALTHOPTIONSET 10

/* AggregatedHealthDataType */
typedef struct {
    UA_DeviceHealthOptionSet aggregatedDeviceHealth;
    UA_OperationalHealthOptionSet aggregatedOperationalHealth;
} UA_AggregatedHealthDataType;

#define UA_TYPES_UAFX_AC_AGGREGATEDHEALTHDATATYPE 11

/* ApplicationIdentifierDataType */
typedef struct {
    UA_LocalizedText name;
    UA_ApplicationId uniqueIdentifier;
} UA_ApplicationIdentifierDataType;

#define UA_TYPES_UAFX_AC_APPLICATIONIDENTIFIERDATATYPE 12

/* IntervalRange */
typedef struct {
    UA_UInt32 min;
    UA_UInt32 max;
    UA_UInt16 increment;
    UA_UInt16 multiplier;
    UA_FxTimeUnitsEnum unit;
} UA_IntervalRange;

#define UA_TYPES_UAFX_AC_INTERVALRANGE 13


_UA_END_DECLS

#endif /* TYPES_UAFX_AC_GENERATED_H_ */
